import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Logo } from "@/components/Logo";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#04080f] text-white antialiased">
      <header className="border-b border-white/5 px-6 h-16 flex items-center justify-between max-w-7xl mx-auto">
        <Link href="/"><Logo size={28} textSize="text-base" className="cursor-pointer" /></Link>
        <Link href="/"><span className="flex items-center gap-1.5 text-sm text-white/40 hover:text-white transition-colors cursor-pointer"><ArrowLeft size={14} /> Back to home</span></Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-blue-400 text-xs font-semibold uppercase tracking-widest mb-3">Legal</p>
        <h1 className="text-4xl font-bold mb-3">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: January 2025</p>

        <div className="space-y-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>By creating an account or using Light Speed Ghost ("the Platform"), you agree to these Terms of Service. If you do not agree, do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">2. What Light Speed Ghost Is</h2>
            <p>Light Speed Ghost is an AI-assisted academic writing tool. It functions as a writing aid — similar to Grammarly, tutoring services, or study groups — and is designed to help students research, draft, revise, and understand academic material. All generated content is a starting point; you are responsible for reviewing and editing it before any submission.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">3. Academic Integrity</h2>
            <p className="mb-3">You are solely responsible for how you use content generated by the Platform. Light Speed Ghost does not encourage academic dishonesty, plagiarism, or violating your institution's academic integrity policies. By using the Platform, you agree to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Review all generated content before submitting it</li>
              <li>Edit and make generated content genuinely your own</li>
              <li>Comply with your institution's academic integrity policies</li>
              <li>Accept full responsibility for any content you submit academically</li>
            </ul>
            <p className="mt-3">See our full <Link href="/academic-use"><span className="text-blue-400 hover:text-blue-300 cursor-pointer">Academic Use Policy</span></Link>.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">4. Eligibility</h2>
            <p>You must be at least 13 years old to use the Platform. If you are under 18, you represent that you have parental or guardian consent.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">5. Account Responsibilities</h2>
            <p>You are responsible for maintaining the security of your account credentials. You agree not to share your account, use it commercially without authorization, or use it to generate harmful, abusive, or illegal content.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">6. Subscriptions and Billing</h2>
            <p>The Starter plan is $4.99/month. Pro and Campus plans are billed monthly or annually. You may cancel at any time; cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months. Pricing is subject to change with 30 days notice.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">7. Intellectual Property</h2>
            <p>You retain ownership of content you submit to the Platform. Light Speed Ghost retains ownership of the platform, its design, algorithms, and branding. Content generated by AI on your behalf is provided for your personal, educational use.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">8. Limitation of Liability</h2>
            <p>The Platform is provided "as is." We make no warranties about the accuracy, completeness, or fitness of generated content. We are not liable for any academic consequences resulting from your use of the Platform. Our total liability to you shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">9. Termination</h2>
            <p>We may suspend or terminate accounts that violate these terms, engage in abuse, or use the Platform for prohibited purposes. You may delete your account at any time.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">10. Governing Law</h2>
            <p>These Terms are governed by the laws of the State of California, USA. Disputes shall be resolved in courts located in San Mateo County, California.</p>
          </section>

          <section>
            <h2 className="text-white text-xl font-semibold mb-4">11. Contact</h2>
            <p>Questions? Email <a href="mailto:info@lightspeedghost.com" className="text-blue-400 hover:text-blue-300">info@lightspeedghost.com</a> or write to us at 500 Oracle Pkwy, Redwood City, CA 94065.</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/5 py-8 px-6 text-center">
        <p className="text-white/25 text-xs">© {new Date().getFullYear()} Light Speed Ghost. All rights reserved.</p>
      </footer>
    </div>
  );
}
