/**
 * Authoritative source registry — a large, curated allowlist of REAL, verifiable
 * institutions and outlets the system is told to ground finance / markets /
 * current-events answers in, so it can't invent figures, dates, or events. Every
 * entry is a genuine organisation with its primary domain. Coverage spans every
 * region of the world and the categories that matter for grounding:
 *
 *   markets-data · financial-news · general-news · central-bank · regulator ·
 *   exchange · statistics · multilateral · government · ratings-research ·
 *   commodities-energy · crypto
 *
 * The rule enforced downstream (see grounding.ts): for any number, price,
 * statistic, date, or claimed current event, cite one of these by name; if the
 * data can't be verified against them or the live feed, SAY SO — never fabricate.
 */

export type SourceRegion =
  | "Global" | "North America" | "Europe" | "Asia" | "Africa"
  | "Middle East" | "Latin America" | "Oceania";

export type SourceCategory =
  | "markets-data" | "financial-news" | "general-news" | "central-bank"
  | "regulator" | "exchange" | "statistics" | "multilateral" | "government"
  | "ratings-research" | "commodities-energy" | "crypto";

export interface AuthoritativeSource {
  name: string;
  url: string;
  region: SourceRegion;
  category: SourceCategory;
}

const S = (category: SourceCategory, rows: [string, string, SourceRegion][]): AuthoritativeSource[] =>
  rows.map(([name, url, region]) => ({ name, url, region, category }));

export const AUTHORITATIVE_SOURCES: AuthoritativeSource[] = [
  // ── Markets data & terminals ────────────────────────────────────────────────
  ...S("markets-data", [
    ["Yahoo Finance", "https://finance.yahoo.com", "Global"],
    ["Bloomberg", "https://www.bloomberg.com", "Global"],
    ["Bloomberg Markets", "https://www.bloomberg.com/markets", "Global"],
    ["Refinitiv (LSEG Data & Analytics)", "https://www.lseg.com/en/data-analytics", "Global"],
    ["Morningstar", "https://www.morningstar.com", "Global"],
    ["MarketWatch", "https://www.marketwatch.com", "Global"],
    ["Investing.com", "https://www.investing.com", "Global"],
    ["Google Finance", "https://www.google.com/finance", "Global"],
    ["CNBC Markets", "https://www.cnbc.com/markets", "Global"],
    ["Nasdaq Market Data", "https://www.nasdaq.com/market-activity", "North America"],
    ["FactSet", "https://www.factset.com", "Global"],
    ["S&P Capital IQ", "https://www.capitaliq.spglobal.com", "Global"],
    ["Trading Economics", "https://tradingeconomics.com", "Global"],
    ["Statista", "https://www.statista.com", "Global"],
    ["Koyfin", "https://www.koyfin.com", "Global"],
    ["Seeking Alpha", "https://seekingalpha.com", "Global"],
    ["TipRanks", "https://www.tipranks.com", "Global"],
    ["Stockopedia", "https://www.stockopedia.com", "Europe"],
    ["Simply Wall St", "https://simplywall.st", "Oceania"],
    ["Finviz", "https://finviz.com", "North America"],
    ["TradingView", "https://www.tradingview.com", "Global"],
    ["Wisesheets", "https://wisesheets.io", "Global"],
    ["YCharts", "https://ycharts.com", "North America"],
    ["Macrotrends", "https://www.macrotrends.net", "Global"],
    ["FRED (St. Louis Fed data)", "https://fred.stlouisfed.org", "North America"],
    ["World Government Bonds", "https://www.worldgovernmentbonds.com", "Global"],
    ["Cbonds", "https://cbonds.com", "Global"],
    ["Dividend.com", "https://www.dividend.com", "North America"],
    ["Barchart", "https://www.barchart.com", "North America"],
    ["Quandl (Nasdaq Data Link)", "https://data.nasdaq.com", "Global"],
    ["Financial Modeling Prep", "https://financialmodelingprep.com", "Global"],
    ["Alpha Vantage", "https://www.alphavantage.co", "Global"],
    ["Twelve Data", "https://twelvedata.com", "Global"],
    ["IEX Cloud", "https://iexcloud.io", "North America"],
    ["Wall Street Journal Markets", "https://www.wsj.com/market-data", "North America"],
    ["Financial Times Markets Data", "https://markets.ft.com", "Europe"],
    ["Euronext Live Markets", "https://live.euronext.com", "Europe"],
    ["Börse Frankfurt Data", "https://www.boerse-frankfurt.de", "Europe"],
    ["Investing.com India", "https://in.investing.com", "Asia"],
    ["Moneycontrol Markets", "https://www.moneycontrol.com/markets", "Asia"],
    ["JQuants (Japan Exchange data)", "https://jpx-jquants.com", "Asia"],
    ["East Money (东方财富)", "https://www.eastmoney.com", "Asia"],
    ["Sina Finance (新浪财经)", "https://finance.sina.com.cn", "Asia"],
  ]),

  // ── Financial & business news ───────────────────────────────────────────────
  ...S("financial-news", [
    ["Reuters", "https://www.reuters.com", "Global"],
    ["Reuters Business", "https://www.reuters.com/business", "Global"],
    ["Financial Times", "https://www.ft.com", "Europe"],
    ["The Wall Street Journal", "https://www.wsj.com", "North America"],
    ["The Economist", "https://www.economist.com", "Global"],
    ["Bloomberg Businessweek", "https://www.bloomberg.com/businessweek", "Global"],
    ["Barron's", "https://www.barrons.com", "North America"],
    ["Forbes", "https://www.forbes.com", "Global"],
    ["Fortune", "https://fortune.com", "Global"],
    ["Business Insider", "https://www.businessinsider.com", "Global"],
    ["CNBC", "https://www.cnbc.com", "Global"],
    ["Fox Business", "https://www.foxbusiness.com", "North America"],
    ["The Motley Fool", "https://www.fool.com", "North America"],
    ["Kiplinger", "https://www.kiplinger.com", "North America"],
    ["Institutional Investor", "https://www.institutionalinvestor.com", "Global"],
    ["Pensions & Investments", "https://www.pionline.com", "North America"],
    ["American Banker", "https://www.americanbanker.com", "North America"],
    ["The Banker", "https://www.thebanker.com", "Europe"],
    ["Euromoney", "https://www.euromoney.com", "Europe"],
    ["Financial News London", "https://www.fnlondon.com", "Europe"],
    ["City A.M.", "https://www.cityam.com", "Europe"],
    ["This is Money", "https://www.thisismoney.co.uk", "Europe"],
    ["Handelsblatt", "https://www.handelsblatt.com", "Europe"],
    ["Börsen-Zeitung", "https://www.boersen-zeitung.de", "Europe"],
    ["Les Échos", "https://www.lesechos.fr", "Europe"],
    ["La Tribune", "https://www.latribune.fr", "Europe"],
    ["Il Sole 24 Ore", "https://www.ilsole24ore.com", "Europe"],
    ["Expansión", "https://www.expansion.com", "Europe"],
    ["Cinco Días", "https://cincodias.elpais.com", "Europe"],
    ["Het Financieele Dagblad", "https://fd.nl", "Europe"],
    ["Dagens Industri", "https://www.di.se", "Europe"],
    ["RBC (РБК)", "https://www.rbc.ru", "Europe"],
    ["Nikkei Asia", "https://asia.nikkei.com", "Asia"],
    ["The Nikkei (日本経済新聞)", "https://www.nikkei.com", "Asia"],
    ["South China Morning Post Business", "https://www.scmp.com/business", "Asia"],
    ["Caixin Global", "https://www.caixinglobal.com", "Asia"],
    ["Yicai Global (第一财经)", "https://www.yicaiglobal.com", "Asia"],
    ["The Economic Times", "https://economictimes.indiatimes.com", "Asia"],
    ["Business Standard", "https://www.business-standard.com", "Asia"],
    ["Mint (Livemint)", "https://www.livemint.com", "Asia"],
    ["Moneycontrol", "https://www.moneycontrol.com", "Asia"],
    ["The Business Times (Singapore)", "https://www.businesstimes.com.sg", "Asia"],
    ["Nikkei Markets", "https://www.nikkei.com/markets", "Asia"],
    ["The Korea Economic Daily", "https://www.kedglobal.com", "Asia"],
    ["Maeil Business (매일경제)", "https://www.mk.co.kr", "Asia"],
    ["DealStreetAsia", "https://www.dealstreetasia.com", "Asia"],
    ["Australian Financial Review", "https://www.afr.com", "Oceania"],
    ["The Business Times NZ (BusinessDesk)", "https://businessdesk.co.nz", "Oceania"],
    ["Business Day (South Africa)", "https://www.businesslive.co.za/bd", "Africa"],
    ["Moneyweb", "https://www.moneyweb.co.za", "Africa"],
    ["BusinessDay Nigeria", "https://businessday.ng", "Africa"],
    ["Nairametrics", "https://nairametrics.com", "Africa"],
    ["Business Daily Africa (Kenya)", "https://www.businessdailyafrica.com", "Africa"],
    ["The Africa Report", "https://www.theafricareport.com", "Africa"],
    ["African Business", "https://african.business", "Africa"],
    ["Ventures Africa", "https://venturesafrica.com", "Africa"],
    ["Valor Econômico (Brazil)", "https://valor.globo.com", "Latin America"],
    ["El Financiero (Mexico)", "https://www.elfinanciero.com.mx", "Latin America"],
    ["El Economista (Mexico)", "https://www.eleconomista.com.mx", "Latin America"],
    ["América Economía", "https://www.americaeconomia.com", "Latin America"],
    ["BNamericas", "https://www.bnamericas.com", "Latin America"],
    ["Bloomberg Línea", "https://www.bloomberglinea.com", "Latin America"],
    ["Zawya (Middle East business)", "https://www.zawya.com", "Middle East"],
    ["Arabian Business", "https://www.arabianbusiness.com", "Middle East"],
    ["MEED (Middle East Economic Digest)", "https://www.meed.com", "Middle East"],
    ["Gulf Business", "https://gulfbusiness.com", "Middle East"],
    ["Globes (Israel business)", "https://en.globes.co.il", "Middle East"],
    ["MarketScreener", "https://www.marketscreener.com", "Global"],
    ["Benzinga", "https://www.benzinga.com", "North America"],
    ["TheStreet", "https://www.thestreet.com", "North America"],
    ["Quartz", "https://qz.com", "Global"],
    ["Semafor Business", "https://www.semafor.com/vertical/business", "Global"],
  ]),

  // ── General news (wires + major outlets, every continent) ───────────────────
  ...S("general-news", [
    ["Associated Press", "https://apnews.com", "Global"],
    ["Agence France-Presse", "https://www.afp.com", "Global"],
    ["Reuters World", "https://www.reuters.com/world", "Global"],
    ["BBC News", "https://www.bbc.com/news", "Europe"],
    ["The Guardian", "https://www.theguardian.com", "Europe"],
    ["The New York Times", "https://www.nytimes.com", "North America"],
    ["The Washington Post", "https://www.washingtonpost.com", "North America"],
    ["USA Today", "https://www.usatoday.com", "North America"],
    ["Los Angeles Times", "https://www.latimes.com", "North America"],
    ["NPR", "https://www.npr.org", "North America"],
    ["PBS NewsHour", "https://www.pbs.org/newshour", "North America"],
    ["ABC News (US)", "https://abcnews.go.com", "North America"],
    ["CBS News", "https://www.cbsnews.com", "North America"],
    ["NBC News", "https://www.nbcnews.com", "North America"],
    ["CNN", "https://www.cnn.com", "North America"],
    ["Politico", "https://www.politico.com", "North America"],
    ["Axios", "https://www.axios.com", "North America"],
    ["The Hill", "https://thehill.com", "North America"],
    ["ProPublica", "https://www.propublica.org", "North America"],
    ["The Globe and Mail (Canada)", "https://www.theglobeandmail.com", "North America"],
    ["CBC News (Canada)", "https://www.cbc.ca/news", "North America"],
    ["National Post (Canada)", "https://nationalpost.com", "North America"],
    ["The Times (UK)", "https://www.thetimes.co.uk", "Europe"],
    ["The Telegraph", "https://www.telegraph.co.uk", "Europe"],
    ["The Independent", "https://www.independent.co.uk", "Europe"],
    ["Sky News", "https://news.sky.com", "Europe"],
    ["Channel 4 News", "https://www.channel4.com/news", "Europe"],
    ["Deutsche Welle", "https://www.dw.com", "Europe"],
    ["Der Spiegel", "https://www.spiegel.de", "Europe"],
    ["Frankfurter Allgemeine (FAZ)", "https://www.faz.net", "Europe"],
    ["Süddeutsche Zeitung", "https://www.sueddeutsche.de", "Europe"],
    ["Die Zeit", "https://www.zeit.de", "Europe"],
    ["France 24", "https://www.france24.com", "Europe"],
    ["Le Monde", "https://www.lemonde.fr", "Europe"],
    ["Le Figaro", "https://www.lefigaro.fr", "Europe"],
    ["Libération", "https://www.liberation.fr", "Europe"],
    ["RFI (Radio France Internationale)", "https://www.rfi.fr", "Europe"],
    ["El País (Spain)", "https://elpais.com", "Europe"],
    ["El Mundo (Spain)", "https://www.elmundo.es", "Europe"],
    ["La Vanguardia", "https://www.lavanguardia.com", "Europe"],
    ["Corriere della Sera", "https://www.corriere.it", "Europe"],
    ["la Repubblica", "https://www.repubblica.it", "Europe"],
    ["ANSA (Italy)", "https://www.ansa.it", "Europe"],
    ["NOS (Netherlands)", "https://nos.nl", "Europe"],
    ["NRC (Netherlands)", "https://www.nrc.nl", "Europe"],
    ["De Standaard (Belgium)", "https://www.standaard.be", "Europe"],
    ["RTBF (Belgium)", "https://www.rtbf.be", "Europe"],
    ["SRF (Switzerland)", "https://www.srf.ch", "Europe"],
    ["Neue Zürcher Zeitung", "https://www.nzz.ch", "Europe"],
    ["ORF (Austria)", "https://orf.at", "Europe"],
    ["Der Standard (Austria)", "https://www.derstandard.at", "Europe"],
    ["Dagens Nyheter (Sweden)", "https://www.dn.se", "Europe"],
    ["SVT Nyheter (Sweden)", "https://www.svt.se/nyheter", "Europe"],
    ["Aftenposten (Norway)", "https://www.aftenposten.no", "Europe"],
    ["NRK (Norway)", "https://www.nrk.no", "Europe"],
    ["Helsingin Sanomat (Finland)", "https://www.hs.fi", "Europe"],
    ["YLE (Finland)", "https://yle.fi/uutiset", "Europe"],
    ["DR (Denmark)", "https://www.dr.dk", "Europe"],
    ["Politiken (Denmark)", "https://politiken.dk", "Europe"],
    ["RTÉ (Ireland)", "https://www.rte.ie/news", "Europe"],
    ["The Irish Times", "https://www.irishtimes.com", "Europe"],
    ["Público (Portugal)", "https://www.publico.pt", "Europe"],
    ["Expresso (Portugal)", "https://expresso.pt", "Europe"],
    ["Kathimerini (Greece)", "https://www.ekathimerini.com", "Europe"],
    ["Gazeta Wyborcza (Poland)", "https://wyborcza.pl", "Europe"],
    ["TVN24 (Poland)", "https://tvn24.pl", "Europe"],
    ["Hospodářské noviny (Czechia)", "https://hn.cz", "Europe"],
    ["HVG (Hungary)", "https://hvg.hu", "Europe"],
    ["The Kyiv Independent", "https://kyivindependent.com", "Europe"],
    ["Meduza", "https://meduza.io", "Europe"],
    ["The Moscow Times", "https://www.themoscowtimes.com", "Europe"],
    ["Euronews", "https://www.euronews.com", "Europe"],
    ["Politico Europe", "https://www.politico.eu", "Europe"],
    ["Al Jazeera", "https://www.aljazeera.com", "Middle East"],
    ["The National (UAE)", "https://www.thenationalnews.com", "Middle East"],
    ["Gulf News", "https://gulfnews.com", "Middle East"],
    ["Arab News", "https://www.arabnews.com", "Middle East"],
    ["Haaretz", "https://www.haaretz.com", "Middle East"],
    ["The Times of Israel", "https://www.timesofisrael.com", "Middle East"],
    ["The Jerusalem Post", "https://www.jpost.com", "Middle East"],
    ["Middle East Eye", "https://www.middleeasteye.net", "Middle East"],
    ["Al-Monitor", "https://www.al-monitor.com", "Middle East"],
    ["Daily Sabah (Turkey)", "https://www.dailysabah.com", "Middle East"],
    ["Hürriyet Daily News (Turkey)", "https://www.hurriyetdailynews.com", "Middle East"],
    ["Tehran Times", "https://www.tehrantimes.com", "Middle East"],
    ["The Xinhua News Agency", "https://english.news.cn", "Asia"],
    ["China Daily", "https://www.chinadaily.com.cn", "Asia"],
    ["Global Times", "https://www.globaltimes.cn", "Asia"],
    ["South China Morning Post", "https://www.scmp.com", "Asia"],
    ["The Japan Times", "https://www.japantimes.co.jp", "Asia"],
    ["NHK World", "https://www3.nhk.or.jp/nhkworld", "Asia"],
    ["The Asahi Shimbun", "https://www.asahi.com/ajw", "Asia"],
    ["Yonhap News (Korea)", "https://en.yna.co.kr", "Asia"],
    ["The Korea Herald", "https://www.koreaherald.com", "Asia"],
    ["The Times of India", "https://timesofindia.indiatimes.com", "Asia"],
    ["The Hindu", "https://www.thehindu.com", "Asia"],
    ["Hindustan Times", "https://www.hindustantimes.com", "Asia"],
    ["NDTV", "https://www.ndtv.com", "Asia"],
    ["The Indian Express", "https://indianexpress.com", "Asia"],
    ["Dawn (Pakistan)", "https://www.dawn.com", "Asia"],
    ["The Daily Star (Bangladesh)", "https://www.thedailystar.net", "Asia"],
    ["The Straits Times (Singapore)", "https://www.straitstimes.com", "Asia"],
    ["Channel NewsAsia", "https://www.channelnewsasia.com", "Asia"],
    ["The Jakarta Post", "https://www.thejakartapost.com", "Asia"],
    ["Bangkok Post", "https://www.bangkokpost.com", "Asia"],
    ["The Star (Malaysia)", "https://www.thestar.com.my", "Asia"],
    ["Philippine Daily Inquirer", "https://www.inquirer.net", "Asia"],
    ["VnExpress (Vietnam)", "https://e.vnexpress.net", "Asia"],
    ["Taipei Times", "https://www.taipeitimes.com", "Asia"],
    ["ABC News (Australia)", "https://www.abc.net.au/news", "Oceania"],
    ["The Sydney Morning Herald", "https://www.smh.com.au", "Oceania"],
    ["The Age (Australia)", "https://www.theage.com.au", "Oceania"],
    ["The Australian", "https://www.theaustralian.com.au", "Oceania"],
    ["Radio New Zealand (RNZ)", "https://www.rnz.co.nz", "Oceania"],
    ["The New Zealand Herald", "https://www.nzherald.co.nz", "Oceania"],
    ["Stuff (New Zealand)", "https://www.stuff.co.nz", "Oceania"],
    ["Al Jazeera Africa", "https://www.aljazeera.com/africa", "Africa"],
    ["BBC News Africa", "https://www.bbc.com/news/world/africa", "Africa"],
    ["The Africa Report News", "https://www.theafricareport.com", "Africa"],
    ["Mail & Guardian (South Africa)", "https://mg.co.za", "Africa"],
    ["News24 (South Africa)", "https://www.news24.com", "Africa"],
    ["Daily Maverick (South Africa)", "https://www.dailymaverick.co.za", "Africa"],
    ["The Punch (Nigeria)", "https://punchng.com", "Africa"],
    ["Premium Times (Nigeria)", "https://www.premiumtimesng.com", "Africa"],
    ["The Guardian Nigeria", "https://guardian.ng", "Africa"],
    ["Daily Nation (Kenya)", "https://nation.africa", "Africa"],
    ["The Standard (Kenya)", "https://www.standardmedia.co.ke", "Africa"],
    ["The EastAfrican", "https://www.theeastafrican.co.ke", "Africa"],
    ["Graphic Online (Ghana)", "https://www.graphic.com.gh", "Africa"],
    ["Ahram Online (Egypt)", "https://english.ahram.org.eg", "Africa"],
    ["Ethiopian Reporter", "https://www.thereporterethiopia.com", "Africa"],
    ["The Herald (Zimbabwe)", "https://www.herald.co.zw", "Africa"],
    ["New Vision (Uganda)", "https://www.newvision.co.ug", "Africa"],
    ["The Citizen (Tanzania)", "https://www.thecitizen.co.tz", "Africa"],
    ["Jeune Afrique", "https://www.jeuneafrique.com", "Africa"],
    ["allAfrica", "https://allafrica.com", "Africa"],
    ["O Globo (Brazil)", "https://oglobo.globo.com", "Latin America"],
    ["Folha de S.Paulo", "https://www.folha.uol.com.br", "Latin America"],
    ["Estadão (Brazil)", "https://www.estadao.com.br", "Latin America"],
    ["Clarín (Argentina)", "https://www.clarin.com", "Latin America"],
    ["La Nación (Argentina)", "https://www.lanacion.com.ar", "Latin America"],
    ["El Universal (Mexico)", "https://www.eluniversal.com.mx", "Latin America"],
    ["Milenio (Mexico)", "https://www.milenio.com", "Latin America"],
    ["El Tiempo (Colombia)", "https://www.eltiempo.com", "Latin America"],
    ["El Comercio (Peru)", "https://elcomercio.pe", "Latin America"],
    ["El Mercurio (Chile)", "https://www.elmercurio.com", "Latin America"],
    ["La Tercera (Chile)", "https://www.latercera.com", "Latin America"],
    ["Infobae", "https://www.infobae.com", "Latin America"],
    ["MercoPress", "https://en.mercopress.com", "Latin America"],
  ]),

  // ── Central banks ───────────────────────────────────────────────────────────
  ...S("central-bank", [
    ["U.S. Federal Reserve", "https://www.federalreserve.gov", "North America"],
    ["European Central Bank", "https://www.ecb.europa.eu", "Europe"],
    ["Bank of England", "https://www.bankofengland.co.uk", "Europe"],
    ["Bank of Japan", "https://www.boj.or.jp/en", "Asia"],
    ["People's Bank of China", "http://www.pbc.gov.cn/en", "Asia"],
    ["Reserve Bank of India", "https://www.rbi.org.in", "Asia"],
    ["Bank of Canada", "https://www.bankofcanada.ca", "North America"],
    ["Reserve Bank of Australia", "https://www.rba.gov.au", "Oceania"],
    ["Reserve Bank of New Zealand", "https://www.rbnz.govt.nz", "Oceania"],
    ["Swiss National Bank", "https://www.snb.ch", "Europe"],
    ["Deutsche Bundesbank", "https://www.bundesbank.de", "Europe"],
    ["Banque de France", "https://www.banque-france.fr", "Europe"],
    ["Banca d'Italia", "https://www.bancaditalia.it", "Europe"],
    ["Banco de España", "https://www.bde.es", "Europe"],
    ["De Nederlandsche Bank", "https://www.dnb.nl", "Europe"],
    ["National Bank of Belgium", "https://www.nbb.be", "Europe"],
    ["Sveriges Riksbank", "https://www.riksbank.se", "Europe"],
    ["Norges Bank", "https://www.norges-bank.no", "Europe"],
    ["Danmarks Nationalbank", "https://www.nationalbanken.dk", "Europe"],
    ["Bank of Finland", "https://www.suomenpankki.fi", "Europe"],
    ["Central Bank of Ireland", "https://www.centralbank.ie", "Europe"],
    ["Bank of Greece", "https://www.bankofgreece.gr", "Europe"],
    ["Banco de Portugal", "https://www.bportugal.pt", "Europe"],
    ["Austrian National Bank (OeNB)", "https://www.oenb.at", "Europe"],
    ["National Bank of Poland", "https://nbp.pl", "Europe"],
    ["Czech National Bank", "https://www.cnb.cz", "Europe"],
    ["Magyar Nemzeti Bank (Hungary)", "https://www.mnb.hu", "Europe"],
    ["Bank of Russia", "https://www.cbr.ru", "Europe"],
    ["National Bank of Ukraine", "https://bank.gov.ua", "Europe"],
    ["Central Bank of Turkey (CBRT)", "https://www.tcmb.gov.tr", "Middle East"],
    ["Bank of Korea", "https://www.bok.or.kr", "Asia"],
    ["Monetary Authority of Singapore", "https://www.mas.gov.sg", "Asia"],
    ["Hong Kong Monetary Authority", "https://www.hkma.gov.hk", "Asia"],
    ["Bank Indonesia", "https://www.bi.go.id", "Asia"],
    ["Bank Negara Malaysia", "https://www.bnm.gov.my", "Asia"],
    ["Bank of Thailand", "https://www.bot.or.th", "Asia"],
    ["Bangko Sentral ng Pilipinas", "https://www.bsp.gov.ph", "Asia"],
    ["State Bank of Vietnam", "https://www.sbv.gov.vn", "Asia"],
    ["Central Bank of the Republic of China (Taiwan)", "https://www.cbc.gov.tw", "Asia"],
    ["State Bank of Pakistan", "https://www.sbp.org.pk", "Asia"],
    ["Bangladesh Bank", "https://www.bb.org.bd", "Asia"],
    ["Central Bank of Sri Lanka", "https://www.cbsl.gov.lk", "Asia"],
    ["Saudi Central Bank (SAMA)", "https://www.sama.gov.sa", "Middle East"],
    ["Central Bank of the UAE", "https://www.centralbank.ae", "Middle East"],
    ["Qatar Central Bank", "https://www.qcb.gov.qa", "Middle East"],
    ["Central Bank of Kuwait", "https://www.cbk.gov.kw", "Middle East"],
    ["Central Bank of Bahrain", "https://www.cbb.gov.bh", "Middle East"],
    ["Central Bank of Oman", "https://cbo.gov.om", "Middle East"],
    ["Central Bank of Iraq", "https://cbi.iq", "Middle East"],
    ["Central Bank of Jordan", "https://www.cbj.gov.jo", "Middle East"],
    ["Banque du Liban (Lebanon)", "https://www.bdl.gov.lb", "Middle East"],
    ["Central Bank of Egypt", "https://www.cbe.org.eg", "Africa"],
    ["South African Reserve Bank", "https://www.resbank.co.za", "Africa"],
    ["Central Bank of Nigeria", "https://www.cbn.gov.ng", "Africa"],
    ["Central Bank of Kenya", "https://www.centralbank.go.ke", "Africa"],
    ["Bank of Ghana", "https://www.bog.gov.gh", "Africa"],
    ["Bank of Tanzania", "https://www.bot.go.tz", "Africa"],
    ["Bank of Uganda", "https://www.bou.or.ug", "Africa"],
    ["National Bank of Rwanda", "https://www.bnr.rw", "Africa"],
    ["Bank of Zambia", "https://www.boz.zm", "Africa"],
    ["Reserve Bank of Zimbabwe", "https://www.rbz.co.zw", "Africa"],
    ["Bank of Mauritius", "https://www.bom.mu", "Africa"],
    ["Bank Al-Maghrib (Morocco)", "https://www.bkam.ma", "Africa"],
    ["Central Bank of Tunisia", "https://www.bct.gov.tn", "Africa"],
    ["Bank of Algeria", "https://www.bank-of-algeria.dz", "Africa"],
    ["Central Bank of West African States (BCEAO)", "https://www.bceao.int", "Africa"],
    ["Bank of Central African States (BEAC)", "https://www.beac.int", "Africa"],
    ["U.S. Federal Reserve Bank of New York", "https://www.newyorkfed.org", "North America"],
    ["Banco de México", "https://www.banxico.org.mx", "Latin America"],
    ["Banco Central do Brasil", "https://www.bcb.gov.br", "Latin America"],
    ["Banco Central de la República Argentina", "https://www.bcra.gob.ar", "Latin America"],
    ["Banco Central de Chile", "https://www.bcentral.cl", "Latin America"],
    ["Banco de la República (Colombia)", "https://www.banrep.gov.co", "Latin America"],
    ["Banco Central de Reserva del Perú", "https://www.bcrp.gob.pe", "Latin America"],
    ["Banco Central del Uruguay", "https://www.bcu.gub.uy", "Latin America"],
    ["Banco Central del Ecuador", "https://www.bce.fin.ec", "Latin America"],
    ["Banco Central de Costa Rica", "https://www.bccr.fi.cr", "Latin America"],
    ["Bank for International Settlements (central-bank directory)", "https://www.bis.org/cbanks.htm", "Global"],
  ]),

  // ── Financial & market regulators ───────────────────────────────────────────
  ...S("regulator", [
    ["U.S. Securities and Exchange Commission (SEC)", "https://www.sec.gov", "North America"],
    ["SEC EDGAR filings", "https://www.sec.gov/edgar", "North America"],
    ["FINRA", "https://www.finra.org", "North America"],
    ["U.S. Commodity Futures Trading Commission (CFTC)", "https://www.cftc.gov", "North America"],
    ["U.S. Federal Deposit Insurance Corporation (FDIC)", "https://www.fdic.gov", "North America"],
    ["U.S. Office of the Comptroller of the Currency (OCC)", "https://www.occ.gov", "North America"],
    ["Consumer Financial Protection Bureau", "https://www.consumerfinance.gov", "North America"],
    ["Ontario Securities Commission", "https://www.osc.ca", "North America"],
    ["Financial Conduct Authority (UK)", "https://www.fca.org.uk", "Europe"],
    ["Prudential Regulation Authority (UK)", "https://www.bankofengland.co.uk/prudential-regulation", "Europe"],
    ["European Securities and Markets Authority (ESMA)", "https://www.esma.europa.eu", "Europe"],
    ["European Banking Authority (EBA)", "https://www.eba.europa.eu", "Europe"],
    ["BaFin (Germany)", "https://www.bafin.de", "Europe"],
    ["Autorité des marchés financiers (France)", "https://www.amf-france.org", "Europe"],
    ["CONSOB (Italy)", "https://www.consob.it", "Europe"],
    ["CNMV (Spain)", "https://www.cnmv.es", "Europe"],
    ["AFM (Netherlands)", "https://www.afm.nl", "Europe"],
    ["FINMA (Switzerland)", "https://www.finma.ch", "Europe"],
    ["Finansinspektionen (Sweden)", "https://www.fi.se", "Europe"],
    ["Central Bank of Ireland (regulation)", "https://www.centralbank.ie/regulation", "Europe"],
    ["Securities and Exchange Board of India (SEBI)", "https://www.sebi.gov.in", "Asia"],
    ["China Securities Regulatory Commission (CSRC)", "http://www.csrc.gov.cn/csrc_en", "Asia"],
    ["Financial Services Agency (Japan)", "https://www.fsa.go.jp/en", "Asia"],
    ["Securities and Futures Commission (Hong Kong)", "https://www.sfc.hk", "Asia"],
    ["Financial Supervisory Service (Korea)", "https://www.fss.or.kr", "Asia"],
    ["Australian Securities and Investments Commission (ASIC)", "https://asic.gov.au", "Oceania"],
    ["Securities Commission Malaysia", "https://www.sc.com.my", "Asia"],
    ["Otoritas Jasa Keuangan (Indonesia)", "https://www.ojk.go.id", "Asia"],
    ["Securities and Exchange Commission of Pakistan", "https://www.secp.gov.pk", "Asia"],
    ["Capital Markets Authority (Kenya)", "https://www.cma.or.ke", "Africa"],
    ["Securities and Exchange Commission (Nigeria)", "https://sec.gov.ng", "Africa"],
    ["Financial Sector Conduct Authority (South Africa)", "https://www.fsca.co.za", "Africa"],
    ["Comissão de Valores Mobiliários (Brazil)", "https://www.gov.br/cvm", "Latin America"],
    ["Comisión Nacional Bancaria y de Valores (Mexico)", "https://www.gov.mx/cnbv", "Latin America"],
    ["Comisión para el Mercado Financiero (Chile)", "https://www.cmfchile.cl", "Latin America"],
    ["Financial Stability Board", "https://www.fsb.org", "Global"],
    ["International Organization of Securities Commissions (IOSCO)", "https://www.iosco.org", "Global"],
    ["Basel Committee on Banking Supervision", "https://www.bis.org/bcbs", "Global"],
  ]),

  // ── Stock & derivatives exchanges ───────────────────────────────────────────
  ...S("exchange", [
    ["New York Stock Exchange (NYSE)", "https://www.nyse.com", "North America"],
    ["Nasdaq", "https://www.nasdaq.com", "North America"],
    ["Cboe Global Markets", "https://www.cboe.com", "North America"],
    ["CME Group", "https://www.cmegroup.com", "North America"],
    ["Intercontinental Exchange (ICE)", "https://www.ice.com", "North America"],
    ["Toronto Stock Exchange (TMX)", "https://www.tsx.com", "North America"],
    ["London Stock Exchange", "https://www.londonstockexchange.com", "Europe"],
    ["Euronext", "https://www.euronext.com", "Europe"],
    ["Deutsche Börse (Xetra)", "https://www.deutsche-boerse.com", "Europe"],
    ["SIX Swiss Exchange", "https://www.six-group.com", "Europe"],
    ["Nasdaq Nordic", "https://www.nasdaqomxnordic.com", "Europe"],
    ["Borsa Italiana", "https://www.borsaitaliana.it", "Europe"],
    ["BME (Bolsas y Mercados Españoles)", "https://www.bolsasymercados.es", "Europe"],
    ["Wiener Börse (Vienna)", "https://www.wienerborse.at", "Europe"],
    ["Warsaw Stock Exchange (GPW)", "https://www.gpw.pl", "Europe"],
    ["Moscow Exchange (MOEX)", "https://www.moex.com", "Europe"],
    ["Borsa İstanbul", "https://www.borsaistanbul.com", "Middle East"],
    ["Tel Aviv Stock Exchange", "https://www.tase.co.il", "Middle East"],
    ["Saudi Exchange (Tadawul)", "https://www.saudiexchange.sa", "Middle East"],
    ["Abu Dhabi Securities Exchange", "https://www.adx.ae", "Middle East"],
    ["Dubai Financial Market", "https://www.dfm.ae", "Middle East"],
    ["Qatar Stock Exchange", "https://www.qe.com.qa", "Middle East"],
    ["Tokyo Stock Exchange (JPX)", "https://www.jpx.co.jp/english", "Asia"],
    ["Shanghai Stock Exchange", "http://english.sse.com.cn", "Asia"],
    ["Shenzhen Stock Exchange", "https://www.szse.cn/English", "Asia"],
    ["Hong Kong Exchanges (HKEX)", "https://www.hkex.com.hk", "Asia"],
    ["Korea Exchange (KRX)", "https://www.krx.co.kr", "Asia"],
    ["Taiwan Stock Exchange", "https://www.twse.com.tw/en", "Asia"],
    ["National Stock Exchange of India (NSE)", "https://www.nseindia.com", "Asia"],
    ["BSE (Bombay Stock Exchange)", "https://www.bseindia.com", "Asia"],
    ["Singapore Exchange (SGX)", "https://www.sgx.com", "Asia"],
    ["Bursa Malaysia", "https://www.bursamalaysia.com", "Asia"],
    ["Indonesia Stock Exchange (IDX)", "https://www.idx.co.id", "Asia"],
    ["Stock Exchange of Thailand", "https://www.set.or.th", "Asia"],
    ["Philippine Stock Exchange", "https://www.pse.com.ph", "Asia"],
    ["Ho Chi Minh Stock Exchange", "https://www.hsx.vn", "Asia"],
    ["Pakistan Stock Exchange", "https://www.psx.com.pk", "Asia"],
    ["Dhaka Stock Exchange", "https://www.dsebd.org", "Asia"],
    ["Australian Securities Exchange (ASX)", "https://www.asx.com.au", "Oceania"],
    ["NZX (New Zealand Exchange)", "https://www.nzx.com", "Oceania"],
    ["Johannesburg Stock Exchange (JSE)", "https://www.jse.co.za", "Africa"],
    ["Nigerian Exchange Group (NGX)", "https://ngxgroup.com", "Africa"],
    ["Nairobi Securities Exchange", "https://www.nse.co.ke", "Africa"],
    ["Ghana Stock Exchange", "https://gse.com.gh", "Africa"],
    ["Egyptian Exchange (EGX)", "https://www.egx.com.eg", "Africa"],
    ["Casablanca Stock Exchange", "https://www.casablanca-bourse.com", "Africa"],
    ["B3 (Brazil Stock Exchange)", "https://www.b3.com.br", "Latin America"],
    ["Bolsa Mexicana de Valores", "https://www.bmv.com.mx", "Latin America"],
    ["Santiago Stock Exchange (Chile)", "https://www.bolsadesantiago.com", "Latin America"],
    ["Colombia Stock Exchange (bvc)", "https://www.bvc.com.co", "Latin America"],
    ["Lima Stock Exchange (BVL)", "https://www.bvl.com.pe", "Latin America"],
    ["Buenos Aires Stock Exchange (BYMA)", "https://www.byma.com.ar", "Latin America"],
    ["World Federation of Exchanges", "https://www.world-exchanges.org", "Global"],
  ]),

  // ── National statistics offices ─────────────────────────────────────────────
  ...S("statistics", [
    ["U.S. Bureau of Labor Statistics", "https://www.bls.gov", "North America"],
    ["U.S. Bureau of Economic Analysis", "https://www.bea.gov", "North America"],
    ["U.S. Census Bureau", "https://www.census.gov", "North America"],
    ["Statistics Canada", "https://www.statcan.gc.ca", "North America"],
    ["Eurostat", "https://ec.europa.eu/eurostat", "Europe"],
    ["UK Office for National Statistics", "https://www.ons.gov.uk", "Europe"],
    ["Destatis (Germany)", "https://www.destatis.de", "Europe"],
    ["INSEE (France)", "https://www.insee.fr", "Europe"],
    ["ISTAT (Italy)", "https://www.istat.it", "Europe"],
    ["INE (Spain)", "https://www.ine.es", "Europe"],
    ["Statistics Netherlands (CBS)", "https://www.cbs.nl", "Europe"],
    ["Statistics Sweden (SCB)", "https://www.scb.se", "Europe"],
    ["Statistics Norway (SSB)", "https://www.ssb.no", "Europe"],
    ["Statistics Finland", "https://www.stat.fi", "Europe"],
    ["Statistics Denmark", "https://www.dst.dk", "Europe"],
    ["Statistics Poland (GUS)", "https://stat.gov.pl", "Europe"],
    ["Rosstat (Russia)", "https://rosstat.gov.ru", "Europe"],
    ["National Bureau of Statistics of China", "https://www.stats.gov.cn/english", "Asia"],
    ["Statistics Bureau of Japan", "https://www.stat.go.jp/english", "Asia"],
    ["Statistics Korea (KOSTAT)", "https://kostat.go.kr/eng", "Asia"],
    ["Ministry of Statistics (India, MoSPI)", "https://www.mospi.gov.in", "Asia"],
    ["Singapore Department of Statistics", "https://www.singstat.gov.sg", "Asia"],
    ["Statistics Indonesia (BPS)", "https://www.bps.go.id", "Asia"],
    ["Department of Statistics Malaysia", "https://www.dosm.gov.my", "Asia"],
    ["Pakistan Bureau of Statistics", "https://www.pbs.gov.pk", "Asia"],
    ["Bangladesh Bureau of Statistics", "https://bbs.gov.bd", "Asia"],
    ["Australian Bureau of Statistics", "https://www.abs.gov.au", "Oceania"],
    ["Stats NZ", "https://www.stats.govt.nz", "Oceania"],
    ["Statistics South Africa", "https://www.statssa.gov.za", "Africa"],
    ["National Bureau of Statistics (Nigeria)", "https://nigerianstat.gov.ng", "Africa"],
    ["Kenya National Bureau of Statistics", "https://www.knbs.or.ke", "Africa"],
    ["Ghana Statistical Service", "https://www.statsghana.gov.gh", "Africa"],
    ["CAPMAS (Egypt)", "https://www.capmas.gov.eg", "Africa"],
    ["IBGE (Brazil)", "https://www.ibge.gov.br", "Latin America"],
    ["INEGI (Mexico)", "https://www.inegi.org.mx", "Latin America"],
    ["INDEC (Argentina)", "https://www.indec.gob.ar", "Latin America"],
    ["DANE (Colombia)", "https://www.dane.gov.co", "Latin America"],
    ["INE (Chile)", "https://www.ine.gob.cl", "Latin America"],
    ["UN Statistics Division", "https://unstats.un.org", "Global"],
    ["OECD Data", "https://data.oecd.org", "Global"],
    ["World Bank Open Data", "https://data.worldbank.org", "Global"],
  ]),

  // ── Multilateral & intergovernmental ────────────────────────────────────────
  ...S("multilateral", [
    ["International Monetary Fund (IMF)", "https://www.imf.org", "Global"],
    ["World Bank", "https://www.worldbank.org", "Global"],
    ["OECD", "https://www.oecd.org", "Global"],
    ["Bank for International Settlements (BIS)", "https://www.bis.org", "Global"],
    ["World Trade Organization (WTO)", "https://www.wto.org", "Global"],
    ["United Nations", "https://www.un.org", "Global"],
    ["UN Conference on Trade and Development (UNCTAD)", "https://unctad.org", "Global"],
    ["UN Development Programme (UNDP)", "https://www.undp.org", "Global"],
    ["International Labour Organization (ILO)", "https://www.ilo.org", "Global"],
    ["Food and Agriculture Organization (FAO)", "https://www.fao.org", "Global"],
    ["World Health Organization (WHO)", "https://www.who.int", "Global"],
    ["International Energy Agency (IEA)", "https://www.iea.org", "Global"],
    ["OPEC", "https://www.opec.org", "Global"],
    ["World Economic Forum", "https://www.weforum.org", "Global"],
    ["Asian Development Bank", "https://www.adb.org", "Asia"],
    ["African Development Bank", "https://www.afdb.org", "Africa"],
    ["Inter-American Development Bank", "https://www.iadb.org", "Latin America"],
    ["European Investment Bank", "https://www.eib.org", "Europe"],
    ["European Bank for Reconstruction and Development", "https://www.ebrd.com", "Europe"],
    ["European Commission — Economy & Finance", "https://economy-finance.ec.europa.eu", "Europe"],
    ["Eurogroup / Council of the EU", "https://www.consilium.europa.eu", "Europe"],
    ["G20", "https://www.g20.org", "Global"],
    ["Financial Action Task Force (FATF)", "https://www.fatf-gafi.org", "Global"],
    ["International Finance Corporation (IFC)", "https://www.ifc.org", "Global"],
    ["UN Comtrade", "https://comtrade.un.org", "Global"],
    ["World Intellectual Property Organization (WIPO)", "https://www.wipo.int", "Global"],
    ["International Telecommunication Union (ITU)", "https://www.itu.int", "Global"],
    ["World Gold Council", "https://www.gold.org", "Global"],
    ["OECD iLibrary", "https://www.oecd-ilibrary.org", "Global"],
    ["IMF World Economic Outlook", "https://www.imf.org/en/Publications/WEO", "Global"],
  ]),

  // ── Government & official data portals ──────────────────────────────────────
  ...S("government", [
    ["U.S. Department of the Treasury", "https://home.treasury.gov", "North America"],
    ["USA.gov", "https://www.usa.gov", "North America"],
    ["Data.gov", "https://www.data.gov", "North America"],
    ["U.S. Government Accountability Office", "https://www.gao.gov", "North America"],
    ["Congressional Budget Office", "https://www.cbo.gov", "North America"],
    ["U.S. Energy Information Administration", "https://www.eia.gov", "North America"],
    ["U.S. Department of Commerce", "https://www.commerce.gov", "North America"],
    ["HM Treasury (UK)", "https://www.gov.uk/government/organisations/hm-treasury", "Europe"],
    ["GOV.UK", "https://www.gov.uk", "Europe"],
    ["UK Office for Budget Responsibility", "https://obr.uk", "Europe"],
    ["European Union (europa.eu)", "https://european-union.europa.eu", "Europe"],
    ["Federal Ministry of Finance (Germany)", "https://www.bundesfinanzministerium.de", "Europe"],
    ["Ministère de l'Économie (France)", "https://www.economie.gouv.fr", "Europe"],
    ["Government of Canada", "https://www.canada.ca", "North America"],
    ["Australian Treasury", "https://treasury.gov.au", "Oceania"],
    ["Ministry of Finance (India)", "https://finmin.nic.in", "Asia"],
    ["National Development and Reform Commission (China)", "https://en.ndrc.gov.cn", "Asia"],
    ["Ministry of Finance (Japan)", "https://www.mof.go.jp/english", "Asia"],
    ["Ministry of Strategy and Finance (Korea)", "https://english.moef.go.kr", "Asia"],
    ["Government of Singapore", "https://www.gov.sg", "Asia"],
    ["National Treasury (South Africa)", "https://www.treasury.gov.za", "Africa"],
    ["Federal Ministry of Finance (Nigeria)", "https://www.finance.gov.ng", "Africa"],
    ["The National Treasury (Kenya)", "https://www.treasury.go.ke", "Africa"],
    ["Ministério da Fazenda (Brazil)", "https://www.gov.br/fazenda", "Latin America"],
    ["Secretaría de Hacienda (Mexico)", "https://www.gob.mx/hacienda", "Latin America"],
    ["U.S. Internal Revenue Service (IRS)", "https://www.irs.gov", "North America"],
    ["U.S. Small Business Administration", "https://www.sba.gov", "North America"],
    ["World Bank Data Catalog", "https://datacatalog.worldbank.org", "Global"],
    ["Our World in Data", "https://ourworldindata.org", "Global"],
    ["Humanitarian Data Exchange (HDX)", "https://data.humdata.org", "Global"],
  ]),

  // ── Ratings, research & data providers ──────────────────────────────────────
  ...S("ratings-research", [
    ["S&P Global Ratings", "https://www.spglobal.com/ratings", "Global"],
    ["Moody's Ratings", "https://www.moodys.com", "Global"],
    ["Fitch Ratings", "https://www.fitchratings.com", "Global"],
    ["DBRS Morningstar", "https://dbrs.morningstar.com", "Global"],
    ["MSCI", "https://www.msci.com", "Global"],
    ["FTSE Russell", "https://www.lseg.com/en/ftse-russell", "Global"],
    ["S&P Dow Jones Indices", "https://www.spglobal.com/spdji", "Global"],
    ["CRISIL (India)", "https://www.crisil.com", "Asia"],
    ["ICRA (India)", "https://www.icra.in", "Asia"],
    ["Morningstar Research", "https://www.morningstar.com/research", "Global"],
    ["McKinsey Global Institute", "https://www.mckinsey.com/mgi", "Global"],
    ["Bain & Company Insights", "https://www.bain.com/insights", "Global"],
    ["Boston Consulting Group Insights", "https://www.bcg.com/publications", "Global"],
    ["PwC Research & Insights", "https://www.pwc.com/gx/en/insights.html", "Global"],
    ["Deloitte Insights", "https://www2.deloitte.com/insights", "Global"],
    ["EY Insights", "https://www.ey.com/en_gl/insights", "Global"],
    ["KPMG Insights", "https://kpmg.com/xx/en/home/insights.html", "Global"],
    ["Gartner", "https://www.gartner.com", "Global"],
    ["Forrester", "https://www.forrester.com", "Global"],
    ["IDC", "https://www.idc.com", "Global"],
    ["Pew Research Center", "https://www.pewresearch.org", "Global"],
    ["Brookings Institution", "https://www.brookings.edu", "North America"],
    ["Peterson Institute for International Economics", "https://www.piie.com", "North America"],
    ["National Bureau of Economic Research (NBER)", "https://www.nber.org", "North America"],
    ["Bruegel (Europe)", "https://www.bruegel.org", "Europe"],
    ["Chatham House", "https://www.chathamhouse.org", "Europe"],
    ["CEPR / VoxEU", "https://cepr.org", "Europe"],
    ["Conference Board", "https://www.conference-board.org", "Global"],
    ["Moody's Analytics", "https://www.moodysanalytics.com", "Global"],
    ["Oxford Economics", "https://www.oxfordeconomics.com", "Global"],
  ]),

  // ── Commodities & energy ────────────────────────────────────────────────────
  ...S("commodities-energy", [
    ["OPEC Monthly Oil Market Report", "https://www.opec.org/opec_web/en/publications/338.htm", "Global"],
    ["International Energy Agency Oil Market", "https://www.iea.org/topics/oil-market-report", "Global"],
    ["U.S. EIA Petroleum & Other Liquids", "https://www.eia.gov/petroleum", "North America"],
    ["London Metal Exchange (LME)", "https://www.lme.com", "Europe"],
    ["CME Group Commodities", "https://www.cmegroup.com/markets/agriculture.html", "North America"],
    ["Intercontinental Exchange (ICE) Energy", "https://www.ice.com/products/Energy", "North America"],
    ["S&P Global Commodity Insights (Platts)", "https://www.spglobal.com/commodityinsights", "Global"],
    ["Argus Media", "https://www.argusmedia.com", "Global"],
    ["Kitco (precious metals)", "https://www.kitco.com", "North America"],
    ["World Gold Council data", "https://www.gold.org/goldhub", "Global"],
    ["Baltic Exchange (shipping)", "https://www.balticexchange.com", "Europe"],
    ["USDA (U.S. agriculture data)", "https://www.usda.gov", "North America"],
    ["World Bank Commodity Markets (Pink Sheet)", "https://www.worldbank.org/en/research/commodity-markets", "Global"],
    ["Trading Economics Commodities", "https://tradingeconomics.com/commodities", "Global"],
    ["Oilprice.com", "https://oilprice.com", "Global"],
    ["Fastmarkets", "https://www.fastmarkets.com", "Global"],
    ["ICIS (chemicals & energy)", "https://www.icis.com", "Global"],
    ["Rystad Energy", "https://www.rystadenergy.com", "Europe"],
    ["Wood Mackenzie", "https://www.woodmac.com", "Global"],
    ["OPEC+ / IEA World Energy Outlook", "https://www.iea.org/reports/world-energy-outlook-2024", "Global"],
    ["Shanghai Futures Exchange", "https://www.shfe.com.cn/eng", "Asia"],
    ["Dalian Commodity Exchange", "http://www.dce.com.cn/DCE/EnglishVersion", "Asia"],
    ["Multi Commodity Exchange of India (MCX)", "https://www.mcxindia.com", "Asia"],
    ["Chicago Board of Trade (CBOT)", "https://www.cmegroup.com/company/cbot.html", "North America"],
    ["Nymex (New York Mercantile Exchange)", "https://www.cmegroup.com/company/nymex.html", "North America"],
  ]),

  // ── Crypto & digital assets ─────────────────────────────────────────────────
  ...S("crypto", [
    ["CoinMarketCap", "https://coinmarketcap.com", "Global"],
    ["CoinGecko", "https://www.coingecko.com", "Global"],
    ["Messari", "https://messari.io", "Global"],
    ["Glassnode", "https://glassnode.com", "Global"],
    ["Kaiko", "https://www.kaiko.com", "Global"],
    ["The Block", "https://www.theblock.co", "Global"],
    ["CoinDesk", "https://www.coindesk.com", "Global"],
    ["Cointelegraph", "https://cointelegraph.com", "Global"],
    ["Coinbase", "https://www.coinbase.com", "North America"],
    ["Kraken", "https://www.kraken.com", "North America"],
    ["Binance", "https://www.binance.com", "Global"],
    ["Bitstamp", "https://www.bitstamp.net", "Europe"],
    ["Gemini", "https://www.gemini.com", "North America"],
    ["Chainalysis", "https://www.chainalysis.com", "Global"],
    ["DefiLlama", "https://defillama.com", "Global"],
    ["Dune Analytics", "https://dune.com", "Global"],
    ["Etherscan", "https://etherscan.io", "Global"],
    ["CryptoCompare", "https://www.cryptocompare.com", "Global"],
    ["CoinMetrics", "https://coinmetrics.io", "Global"],
    ["Nansen", "https://www.nansen.ai", "Global"],
  ]),

  // ── Extended global coverage — more verifiable institutions & outlets ───────
  ...S("central-bank", [
    ["Bank of Israel", "https://www.boi.org.il", "Middle East"],
    ["National Bank of Kazakhstan", "https://nationalbank.kz", "Asia"],
    ["Central Bank of Uzbekistan", "https://cbu.uz", "Asia"],
    ["Central Bank of Azerbaijan", "https://www.cbar.az", "Asia"],
    ["National Bank of Georgia", "https://nbg.gov.ge", "Europe"],
    ["Central Bank of Armenia", "https://www.cba.am", "Europe"],
    ["Nepal Rastra Bank", "https://www.nrb.org.np", "Asia"],
    ["Bank of Mongolia", "https://www.mongolbank.mn", "Asia"],
    ["National Bank of Cambodia", "https://www.nbc.gov.kh", "Asia"],
    ["Central Bank of Myanmar", "https://www.cbm.gov.mm", "Asia"],
    ["Central Bank of Iran", "https://www.cbi.ir", "Middle East"],
    ["Palestine Monetary Authority", "https://www.pma.ps", "Middle East"],
    ["Central Bank of Cyprus", "https://www.centralbank.cy", "Europe"],
    ["Bank of Lithuania", "https://www.lb.lt", "Europe"],
    ["Latvijas Banka (Latvia)", "https://www.bank.lv", "Europe"],
    ["Eesti Pank (Estonia)", "https://www.eestipank.ee", "Europe"],
    ["National Bank of Slovakia", "https://nbs.sk", "Europe"],
    ["Banka Slovenije", "https://www.bsi.si", "Europe"],
    ["Croatian National Bank", "https://www.hnb.hr", "Europe"],
    ["National Bank of Serbia", "https://www.nbs.rs", "Europe"],
    ["National Bank of Romania", "https://www.bnr.ro", "Europe"],
    ["Bulgarian National Bank", "https://www.bnb.bg", "Europe"],
    ["Central Bank of Iceland", "https://www.cb.is", "Europe"],
    ["Central Bank of Malta", "https://www.centralbankmalta.org", "Europe"],
    ["Central Bank of Luxembourg", "https://www.bcl.lu", "Europe"],
    ["National Bank of Ethiopia", "https://nbe.gov.et", "Africa"],
    ["Bank of Botswana", "https://www.bankofbotswana.bw", "Africa"],
    ["Bank of Namibia", "https://www.bon.com.na", "Africa"],
    ["Reserve Bank of Malawi", "https://www.rbm.mw", "Africa"],
    ["National Bank of Angola", "https://www.bna.ao", "Africa"],
    ["Bank of Mozambique", "https://www.bancomoc.mz", "Africa"],
    ["Bank of Zambia", "https://www.boz.zm", "Africa"],
    ["Bank of Jamaica", "https://boj.org.jm", "Latin America"],
    ["Central Bank of Trinidad and Tobago", "https://www.central-bank.org.tt", "Latin America"],
    ["Central Bank of the Dominican Republic", "https://www.bancentral.gov.do", "Latin America"],
    ["Central Bank of Paraguay", "https://www.bcp.gov.py", "Latin America"],
    ["Central Bank of Bolivia", "https://www.bcb.gob.bo", "Latin America"],
    ["Central Bank of Venezuela", "https://www.bcv.org.ve", "Latin America"],
    ["Bank of Guatemala", "https://www.banguat.gob.gt", "Latin America"],
    ["Central Reserve Bank of El Salvador", "https://www.bcr.gob.sv", "Latin America"],
  ]),
  ...S("exchange", [
    ["Tehran Stock Exchange", "https://en.tse.ir", "Middle East"],
    ["Amman Stock Exchange", "https://www.ase.com.jo", "Middle East"],
    ["Muscat Stock Exchange", "https://www.msx.om", "Middle East"],
    ["Bahrain Bourse", "https://www.bahrainbourse.com", "Middle East"],
    ["Boursa Kuwait", "https://www.boursakuwait.com.kw", "Middle East"],
    ["Dar es Salaam Stock Exchange", "https://www.dse.co.tz", "Africa"],
    ["Uganda Securities Exchange", "https://www.use.or.ug", "Africa"],
    ["Botswana Stock Exchange", "https://www.bse.co.bw", "Africa"],
    ["Stock Exchange of Mauritius", "https://www.stockexchangeofmauritius.com", "Africa"],
    ["Zimbabwe Stock Exchange", "https://www.zse.co.zw", "Africa"],
    ["BRVM (West Africa regional exchange)", "https://www.brvm.org", "Africa"],
    ["Athens Stock Exchange (ATHEX)", "https://www.athexgroup.gr", "Europe"],
    ["Prague Stock Exchange", "https://www.pse.cz", "Europe"],
    ["Budapest Stock Exchange", "https://www.bse.hu", "Europe"],
    ["Bucharest Stock Exchange", "https://www.bvb.ro", "Europe"],
    ["Zagreb Stock Exchange", "https://zse.hr", "Europe"],
    ["Kazakhstan Stock Exchange (KASE)", "https://kase.kz", "Asia"],
    ["Colombo Stock Exchange", "https://www.cse.lk", "Asia"],
    ["Nepal Stock Exchange", "https://www.nepalstock.com.np", "Asia"],
    ["Jamaica Stock Exchange", "https://www.jamstockex.com", "Latin America"],
    ["Astana International Exchange", "https://aix.kz", "Asia"],
    ["Nasdaq Baltic", "https://nasdaqbaltic.com", "Europe"],
    ["Oslo Børs (Euronext)", "https://www.euronext.com/en/markets/oslo", "Europe"],
    ["Malawi Stock Exchange", "https://mse.co.mw", "Africa"],
    ["Rwanda Stock Exchange", "https://rse.rw", "Africa"],
  ]),
  ...S("statistics", [
    ["Statistics Austria", "https://www.statistik.at", "Europe"],
    ["Statistics Portugal (INE)", "https://www.ine.pt", "Europe"],
    ["Statbel (Belgium)", "https://statbel.fgov.be", "Europe"],
    ["Federal Statistical Office (Switzerland)", "https://www.bfs.admin.ch", "Europe"],
    ["ELSTAT (Greece)", "https://www.statistics.gr", "Europe"],
    ["TurkStat (Turkey)", "https://www.tuik.gov.tr", "Middle East"],
    ["Philippine Statistics Authority", "https://psa.gov.ph", "Asia"],
    ["General Statistics Office of Vietnam", "https://www.gso.gov.vn", "Asia"],
    ["National Statistical Office of Thailand", "http://www.nso.go.th", "Asia"],
    ["GASTAT (Saudi Arabia)", "https://www.stats.gov.sa", "Middle East"],
    ["Central Bureau of Statistics (Israel)", "https://www.cbs.gov.il", "Middle East"],
    ["INEI (Peru)", "https://www.inei.gob.pe", "Latin America"],
    ["INE (Bolivia)", "https://www.ine.gob.bo", "Latin America"],
    ["Uganda Bureau of Statistics", "https://www.ubos.org", "Africa"],
    ["National Bureau of Statistics (Tanzania)", "https://www.nbs.go.tz", "Africa"],
    ["NISR (Rwanda)", "https://www.statistics.gov.rw", "Africa"],
    ["Zambia Statistics Agency", "https://www.zamstats.gov.zm", "Africa"],
    ["Statistics Botswana", "https://www.statsbots.org.bw", "Africa"],
    ["Statistics Iceland", "https://www.statice.is", "Europe"],
    ["Statistics Estonia", "https://www.stat.ee", "Europe"],
  ]),
  ...S("regulator", [
    ["Financial Regulatory Authority (Egypt)", "https://fra.gov.eg", "Africa"],
    ["Capital Markets Board of Turkey (SPK)", "https://www.cmb.gov.tr", "Middle East"],
    ["Securities and Exchange Commission (Thailand)", "https://www.sec.or.th", "Asia"],
    ["Financial Markets Authority (New Zealand)", "https://www.fma.govt.nz", "Oceania"],
    ["Comisión Nacional de Valores (Argentina)", "https://www.argentina.gob.ar/cnv", "Latin America"],
    ["Superintendencia Financiera de Colombia", "https://www.superfinanciera.gov.co", "Latin America"],
    ["Autorité des marchés financiers (Québec)", "https://lautorite.qc.ca", "North America"],
    ["Financial Services Commission (Mauritius)", "https://www.fscmauritius.org", "Africa"],
    ["CySEC (Cyprus)", "https://www.cysec.gov.cy", "Europe"],
    ["Malta Financial Services Authority", "https://www.mfsa.mt", "Europe"],
    ["Financial Supervisory Commission (Taiwan)", "https://www.fsc.gov.tw", "Asia"],
    ["Securities & Exchange Commission (Bangladesh)", "https://sec.gov.bd", "Asia"],
    ["Central Bank of Bahrain (regulation)", "https://www.cbb.gov.bh", "Middle East"],
    ["Dubai Financial Services Authority", "https://www.dfsa.ae", "Middle East"],
    ["Abu Dhabi Global Market (FSRA)", "https://www.adgm.com", "Middle East"],
  ]),
  ...S("multilateral", [
    ["African Union", "https://au.int", "Africa"],
    ["ASEAN", "https://asean.org", "Asia"],
    ["Mercosur", "https://www.mercosur.int", "Latin America"],
    ["ECOWAS", "https://www.ecowas.int", "Africa"],
    ["Arab Monetary Fund", "https://www.amf.org.ae", "Middle East"],
    ["Gulf Cooperation Council", "https://www.gcc-sg.org", "Middle East"],
    ["Caribbean Development Bank", "https://www.caribank.org", "Latin America"],
    ["CAF — Development Bank of Latin America", "https://www.caf.com", "Latin America"],
    ["Islamic Development Bank", "https://www.isdb.org", "Middle East"],
    ["New Development Bank (BRICS)", "https://www.ndb.int", "Global"],
    ["Asian Infrastructure Investment Bank", "https://www.aiib.org", "Asia"],
    ["UN Economic Commission for Africa (UNECA)", "https://www.uneca.org", "Africa"],
    ["UN ECLAC (Latin America & Caribbean)", "https://www.cepal.org", "Latin America"],
    ["UN ESCAP (Asia-Pacific)", "https://www.unescap.org", "Asia"],
    ["World Bank Global Economic Prospects", "https://www.worldbank.org/en/publication/global-economic-prospects", "Global"],
  ]),
  ...S("government", [
    ["data.gov.uk", "https://www.data.gov.uk", "Europe"],
    ["data.europa.eu", "https://data.europa.eu", "Europe"],
    ["data.gov.au (Australia)", "https://data.gov.au", "Oceania"],
    ["data.gov.in (India)", "https://data.gov.in", "Asia"],
    ["data.gov.sg (Singapore)", "https://data.gov.sg", "Asia"],
    ["dados.gov.br (Brazil)", "https://dados.gov.br", "Latin America"],
    ["datos.gob.mx (Mexico)", "https://datos.gob.mx", "Latin America"],
    ["The White House", "https://www.whitehouse.gov", "North America"],
    ["U.S. Congress", "https://www.congress.gov", "North America"],
    ["European Parliament", "https://www.europarl.europa.eu", "Europe"],
    ["UK Parliament", "https://www.parliament.uk", "Europe"],
    ["Reserve Bank of India — Database (DBIE)", "https://data.rbi.org.in", "Asia"],
    ["Bank of England Statistics", "https://www.bankofengland.co.uk/statistics", "Europe"],
    ["European Central Bank Statistical Data Warehouse", "https://data.ecb.europa.eu", "Europe"],
    ["U.S. Federal Reserve Data (DDP)", "https://www.federalreserve.gov/data.htm", "North America"],
  ]),
  ...S("ratings-research", [
    ["RAND Corporation", "https://www.rand.org", "North America"],
    ["Council on Foreign Relations", "https://www.cfr.org", "North America"],
    ["Carnegie Endowment", "https://carnegieendowment.org", "Global"],
    ["Institute for Fiscal Studies (UK)", "https://ifs.org.uk", "Europe"],
    ["NIESR (UK)", "https://www.niesr.ac.uk", "Europe"],
    ["ifo Institute (Germany)", "https://www.ifo.de", "Europe"],
    ["DIW Berlin", "https://www.diw.de", "Europe"],
    ["Kiel Institute for the World Economy", "https://www.ifw-kiel.de", "Europe"],
    ["CEPII (France)", "https://www.cepii.fr", "Europe"],
    ["Observatory of Economic Complexity (OEC)", "https://oec.world", "Global"],
    ["Tax Foundation", "https://taxfoundation.org", "North America"],
    ["Atlantic Council", "https://www.atlanticcouncil.org", "North America"],
    ["Oxford Economics", "https://www.oxfordeconomics.com", "Global"],
    ["Capital Economics", "https://www.capitaleconomics.com", "Global"],
    ["Fitch Solutions / BMI", "https://www.fitchsolutions.com", "Global"],
  ]),
  ...S("markets-data", [
    ["Investopedia", "https://www.investopedia.com", "Global"],
    ["Stock Analysis", "https://stockanalysis.com", "Global"],
    ["MarketBeat", "https://www.marketbeat.com", "North America"],
    ["Zacks Investment Research", "https://www.zacks.com", "North America"],
    ["GuruFocus", "https://www.gurufocus.com", "North America"],
    ["FT Alphaville", "https://www.ft.com/alphaville", "Europe"],
    ["Reuters Breakingviews", "https://www.reuters.com/breakingviews", "Global"],
    ["Wall Street Journal Central Banks", "https://www.wsj.com/economy/central-banking", "North America"],
    ["Bloomberg Economics", "https://www.bloomberg.com/economics", "Global"],
    ["Trading Economics Calendar", "https://tradingeconomics.com/calendar", "Global"],
    ["Investing.com Economic Calendar", "https://www.investing.com/economic-calendar", "Global"],
    ["Forex Factory", "https://www.forexfactory.com", "Global"],
    ["XE Currency", "https://www.xe.com", "Global"],
    ["Wise (mid-market FX rates)", "https://wise.com/gb/currency-converter", "Global"],
    ["OANDA FX", "https://www.oanda.com", "Global"],
  ]),

  // ── Extended news coverage (every continent) ────────────────────────────────
  ...S("general-news", [
    // Africa
    ["The Namibian", "https://www.namibian.com.na", "Africa"],
    ["MyJoyOnline (Ghana)", "https://www.myjoyonline.com", "Africa"],
    ["Daily Monitor (Uganda)", "https://www.monitor.co.ug", "Africa"],
    ["IPP Media (Tanzania)", "https://www.ippmedia.com", "Africa"],
    ["Le Matin (Morocco)", "https://lematin.ma", "Africa"],
    ["Hespress English (Morocco)", "https://en.hespress.com", "Africa"],
    ["Sudan Tribune", "https://sudantribune.com", "Africa"],
    ["Addis Standard (Ethiopia)", "https://addisstandard.com", "Africa"],
    ["Mmegi (Botswana)", "https://www.mmegi.bw", "Africa"],
    ["IOL (South Africa)", "https://www.iol.co.za", "Africa"],
    ["SowetanLIVE (South Africa)", "https://www.sowetanlive.co.za", "Africa"],
    ["Vanguard (Nigeria)", "https://www.vanguardngr.com", "Africa"],
    ["THISDAY (Nigeria)", "https://www.thisdaylive.com", "Africa"],
    ["Channels Television (Nigeria)", "https://www.channelstv.com", "Africa"],
    ["The Star (Kenya)", "https://www.the-star.co.ke", "Africa"],
    ["Capital FM (Kenya)", "https://www.capitalfm.co.ke", "Africa"],
    ["Citizen Digital (Kenya)", "https://www.citizen.digital", "Africa"],
    ["Times of Zambia", "https://www.times.co.zm", "Africa"],
    ["The Nation (Malawi)", "https://mwnation.com", "Africa"],
    // Asia
    ["The Diplomat", "https://thediplomat.com", "Asia"],
    ["Kyodo News (Japan)", "https://english.kyodonews.net", "Asia"],
    ["The Mainichi (Japan)", "https://mainichi.jp/english", "Asia"],
    ["The Chosun Ilbo (Korea)", "https://english.chosun.com", "Asia"],
    ["The Korea Times", "https://www.koreatimes.co.kr", "Asia"],
    ["People's Daily (China)", "http://en.people.cn", "Asia"],
    ["CGTN", "https://www.cgtn.com", "Asia"],
    ["ThePrint (India)", "https://theprint.in", "Asia"],
    ["Scroll.in (India)", "https://scroll.in", "Asia"],
    ["Deccan Herald (India)", "https://www.deccanherald.com", "Asia"],
    ["The Tribune (India)", "https://www.tribuneindia.com", "Asia"],
    ["Geo News (Pakistan)", "https://www.geo.tv", "Asia"],
    ["The Express Tribune (Pakistan)", "https://tribune.com.pk", "Asia"],
    ["Prothom Alo (Bangladesh)", "https://en.prothomalo.com", "Asia"],
    ["Malaysiakini", "https://www.malaysiakini.com", "Asia"],
    ["New Straits Times (Malaysia)", "https://www.nst.com.my", "Asia"],
    ["Rappler (Philippines)", "https://www.rappler.com", "Asia"],
    ["Tuoi Tre News (Vietnam)", "https://tuoitrenews.vn", "Asia"],
    ["The Nation Thailand", "https://www.nationthailand.com", "Asia"],
    ["Focus Taiwan", "https://focustaiwan.tw", "Asia"],
    ["Ada Derana (Sri Lanka)", "https://www.adaderana.lk", "Asia"],
    ["The Kathmandu Post (Nepal)", "https://kathmandupost.com", "Asia"],
    // Europe
    ["EURACTIV", "https://www.euractiv.com", "Europe"],
    ["The Local Europe", "https://www.thelocal.com", "Europe"],
    ["El Confidencial (Spain)", "https://www.elconfidencial.com", "Europe"],
    ["BFM TV (France)", "https://www.bfmtv.com", "Europe"],
    ["Tagesschau (Germany)", "https://www.tagesschau.de", "Europe"],
    ["Rzeczpospolita (Poland)", "https://www.rp.pl", "Europe"],
    ["Index.hu (Hungary)", "https://index.hu", "Europe"],
    ["VG (Norway)", "https://www.vg.no", "Europe"],
    ["RTP (Portugal)", "https://www.rtp.pt", "Europe"],
    ["To Vima (Greece)", "https://www.tovima.gr", "Europe"],
    ["Novaya / Novinky (Czechia)", "https://www.novinky.cz", "Europe"],
    ["Delfi (Baltics)", "https://www.delfi.lt", "Europe"],
    // Middle East
    ["Asharq Al-Awsat (English)", "https://english.aawsat.com", "Middle East"],
    ["Al Arabiya English", "https://english.alarabiya.net", "Middle East"],
    ["The New Arab", "https://www.newarab.com", "Middle East"],
    ["Anadolu Agency (Turkey)", "https://www.aa.com.tr/en", "Middle East"],
    ["TRT World", "https://www.trtworld.com", "Middle East"],
    ["Khaleej Times (UAE)", "https://www.khaleejtimes.com", "Middle East"],
    ["Gulf Times (Qatar)", "https://www.gulf-times.com", "Middle East"],
    ["Saudi Gazette", "https://saudigazette.com.sa", "Middle East"],
    ["Times of Oman", "https://timesofoman.com", "Middle East"],
    ["Rudaw", "https://www.rudaw.net", "Middle East"],
    // Latin America
    ["The Rio Times", "https://www.riotimesonline.com", "Latin America"],
    ["Buenos Aires Times", "https://www.batimes.com.ar", "Latin America"],
    ["Colombia Reports", "https://colombiareports.com", "Latin America"],
    ["The Tico Times (Costa Rica)", "https://ticotimes.net", "Latin America"],
    ["Americas Quarterly", "https://www.americasquarterly.org", "Latin America"],
    ["MercoPress South Atlantic", "https://en.mercopress.com", "Latin America"],
    ["Buenos Aires Herald", "https://buenosairesherald.com", "Latin America"],
    // North America
    ["CTV News (Canada)", "https://www.ctvnews.ca", "North America"],
    ["Toronto Star", "https://www.thestar.com", "North America"],
    ["The Wall Street Journal U.S. News", "https://www.wsj.com/news/us", "North America"],
    ["Reuters U.S.", "https://www.reuters.com/world/us", "North America"],
    // Oceania
    ["SBS News (Australia)", "https://www.sbs.com.au/news", "Oceania"],
    ["news.com.au", "https://www.news.com.au", "Oceania"],
    ["1News (New Zealand)", "https://www.1news.co.nz", "Oceania"],
    ["Newsroom (New Zealand)", "https://newsroom.co.nz", "Oceania"],
    ["The Fiji Times", "https://www.fijitimes.com", "Oceania"],
    ["ABC Pacific", "https://www.abc.net.au/pacific", "Oceania"],
    // Global wires & explainer
    ["Reuters Factbox", "https://www.reuters.com", "Global"],
    ["AP Fact Check", "https://apnews.com/hub/ap-fact-check", "Global"],
    ["BBC Reality Check", "https://www.bbc.com/news/reality_check", "Global"],
    ["Snopes", "https://www.snopes.com", "Global"],
    ["Full Fact (UK)", "https://fullfact.org", "Europe"],
  ]),
  ...S("financial-news", [
    ["Bond Buyer", "https://www.bondbuyer.com", "North America"],
    ["Risk.net", "https://www.risk.net", "Global"],
    ["Global Finance Magazine", "https://gfmag.com", "Global"],
    ["Central Banking", "https://www.centralbanking.com", "Global"],
    ["FinanceAsia", "https://www.financeasia.com", "Asia"],
    ["The Asset", "https://www.theasset.com", "Asia"],
    ["Investment Executive (Canada)", "https://www.investmentexecutive.com", "North America"],
    ["Money Marketing (UK)", "https://www.moneymarketing.co.uk", "Europe"],
    ["Investment Week (UK)", "https://www.investmentweek.co.uk", "Europe"],
    ["Funds Europe", "https://www.funds-europe.com", "Europe"],
    ["Ignites / FundFire (Financial Times)", "https://www.ignites.com", "North America"],
    ["Pensions Age", "https://www.pensionsage.com", "Europe"],
    ["African Markets", "https://www.african-markets.com", "Africa"],
    ["The Africa Report Business", "https://www.theafricareport.com/business", "Africa"],
    ["LatinFinance", "https://www.latinfinance.com", "Latin America"],
    ["Investor's Business Daily", "https://www.investors.com", "North America"],
    ["The Edge Malaysia", "https://theedgemalaysia.com", "Asia"],
  ]),

  // ── Extended coverage #2 — reference, data & analysis ───────────────────────
  ...S("general-news", [
    ["Vox", "https://www.vox.com", "North America"],
    ["The Atlantic", "https://www.theatlantic.com", "North America"],
    ["TIME", "https://time.com", "Global"],
    ["Newsweek", "https://www.newsweek.com", "Global"],
    ["The New Yorker", "https://www.newyorker.com", "North America"],
    ["Foreign Policy", "https://foreignpolicy.com", "Global"],
    ["Foreign Affairs", "https://www.foreignaffairs.com", "Global"],
    ["The Conversation", "https://theconversation.com", "Global"],
    ["Nature News", "https://www.nature.com/news", "Global"],
    ["Science (AAAS)", "https://www.science.org", "Global"],
    ["Scientific American", "https://www.scientificamerican.com", "Global"],
    ["MIT Technology Review", "https://www.technologyreview.com", "Global"],
    ["WIRED", "https://www.wired.com", "Global"],
    ["Ars Technica", "https://arstechnica.com", "Global"],
    ["TechCrunch", "https://techcrunch.com", "Global"],
    ["The Verge", "https://www.theverge.com", "Global"],
    ["Rest of World", "https://restofworld.org", "Global"],
    ["ICIJ (investigative)", "https://www.icij.org", "Global"],
    ["OCCRP (investigative)", "https://www.occrp.org", "Global"],
    ["Bellingcat", "https://www.bellingcat.com", "Global"],
    ["Devex", "https://www.devex.com", "Global"],
    ["Context (Thomson Reuters Foundation)", "https://www.context.news", "Global"],
    ["Le Temps (Switzerland)", "https://www.letemps.ch", "Europe"],
    ["Kommersant (Russia)", "https://www.kommersant.ru", "Europe"],
    ["TASS", "https://tass.com", "Europe"],
    ["Interfax", "https://interfax.com", "Europe"],
    ["Jakarta Globe", "https://jakartaglobe.id", "Asia"],
    ["Vietnam News", "https://vietnamnews.vn", "Asia"],
    ["The Phnom Penh Post", "https://www.phnompenhpost.com", "Asia"],
    ["Dhaka Tribune", "https://www.dhakatribune.com", "Asia"],
    ["The Himalayan Times (Nepal)", "https://thehimalayantimes.com", "Asia"],
    ["Arab Times (Kuwait)", "https://www.arabtimesonline.com", "Middle East"],
    ["The Peninsula (Qatar)", "https://thepeninsulaqatar.com", "Middle East"],
    ["Egypt Independent", "https://www.egyptindependent.com", "Africa"],
    ["The North Africa Post", "https://northafricapost.com", "Africa"],
    ["Semafor Africa", "https://www.semafor.com/vertical/africa", "Africa"],
    ["The Continent (Africa)", "https://www.thecontinent.org", "Africa"],
    ["Página/12 (Argentina)", "https://www.pagina12.com.ar", "Latin America"],
    ["La Jornada (Mexico)", "https://www.jornada.com.mx", "Latin America"],
    ["Semana (Colombia)", "https://www.semana.com", "Latin America"],
    ["El Espectador (Colombia)", "https://www.elespectador.com", "Latin America"],
    ["La República (Peru)", "https://larepublica.pe", "Latin America"],
    ["El Universal (Venezuela)", "https://www.eluniversal.com", "Latin America"],
    ["Tages-Anzeiger (Switzerland)", "https://www.tagesanzeiger.ch", "Europe"],
    ["Full Fact (fact-checking)", "https://fullfact.org", "Europe"],
    ["PolitiFact", "https://www.politifact.com", "North America"],
  ]),
  ...S("markets-data", [
    ["IMF Data", "https://data.imf.org", "Global"],
    ["BIS Statistics", "https://www.bis.org/statistics", "Global"],
    ["Eurostat Database", "https://ec.europa.eu/eurostat/data/database", "Europe"],
    ["Haver Analytics", "https://www.haver.com", "Global"],
    ["CEIC Data", "https://www.ceicdata.com", "Global"],
    ["DBnomics", "https://db.nomics.world", "Global"],
    ["ETF.com", "https://www.etf.com", "North America"],
    ["justETF", "https://www.justetf.com", "Europe"],
    ["Trackinsight", "https://www.trackinsight.com", "Global"],
    ["MarketAxess (bonds)", "https://www.marketaxess.com", "Global"],
    ["Tradeweb", "https://www.tradeweb.com", "Global"],
    ["Bankrate", "https://www.bankrate.com", "North America"],
    ["NerdWallet", "https://www.nerdwallet.com", "North America"],
    ["Morningstar Bonds & Rates", "https://www.morningstar.com/bonds", "Global"],
    ["Currency.com / XE Rates", "https://www.xe.com/currencytables", "Global"],
  ]),
  ...S("commodities-energy", [
    ["U.S. EIA Natural Gas", "https://www.eia.gov/naturalgas", "North America"],
    ["CRU Group", "https://www.crugroup.com", "Global"],
    ["Gas Infrastructure Europe", "https://www.gie.eu", "Europe"],
    ["IRENA (renewables)", "https://www.irena.org", "Global"],
    ["BloombergNEF", "https://about.bnef.com", "Global"],
    ["Ember (energy data)", "https://ember-energy.org", "Global"],
    ["S&P Global Platts Live", "https://www.spglobal.com/commodityinsights/en/market-insights", "Global"],
    ["USDA World Agricultural Supply & Demand (WASDE)", "https://www.usda.gov/oce/commodity/wasde", "North America"],
    ["Comex (metals, CME)", "https://www.cmegroup.com/company/comex.html", "North America"],
    ["Zhengzhou Commodity Exchange", "http://english.czce.com.cn", "Asia"],
  ]),
  ...S("crypto", [
    ["CoinShares Research", "https://coinshares.com", "Global"],
    ["IntoTheBlock", "https://www.intotheblock.com", "Global"],
    ["L2BEAT", "https://l2beat.com", "Global"],
    ["Token Terminal", "https://tokenterminal.com", "Global"],
    ["CryptoQuant", "https://cryptoquant.com", "Global"],
  ]),
  ...S("multilateral", [
    ["IMF eLibrary", "https://www.elibrary.imf.org", "Global"],
    ["World Bank Microdata Library", "https://microdata.worldbank.org", "Global"],
    ["UNdata", "https://data.un.org", "Global"],
    ["ILOSTAT", "https://ilostat.ilo.org", "Global"],
    ["FAOSTAT", "https://www.fao.org/faostat", "Global"],
    ["WTO Stats", "https://stats.wto.org", "Global"],
    ["WHO Global Health Observatory", "https://www.who.int/data/gho", "Global"],
    ["UN World Population Prospects", "https://population.un.org/wpp", "Global"],
    ["UNDP Human Development Reports", "https://hdr.undp.org", "Global"],
    ["Transparency International", "https://www.transparency.org", "Global"],
  ]),
  ...S("statistics", [
    ["FRED International Data", "https://fred.stlouisfed.org/categories/32263", "Global"],
    ["Statistics Canada Data Portal", "https://www150.statcan.gc.ca", "North America"],
    ["ABS Data (Australia)", "https://www.abs.gov.au/statistics", "Oceania"],
    ["Eurostat Euro Indicators", "https://ec.europa.eu/eurostat/web/euro-indicators", "Europe"],
    ["China NBS Data", "https://data.stats.gov.cn/english", "Asia"],
    ["India MoSPI NAD", "https://mospi.gov.in/national-accounts", "Asia"],
    ["Statista Market Insights", "https://www.statista.com/markets", "Global"],
    ["Numbeo (cost of living)", "https://www.numbeo.com", "Global"],
    ["World Inequality Database", "https://wid.world", "Global"],
    ["Gapminder", "https://www.gapminder.org", "Global"],
  ]),
  ...S("ratings-research", [
    ["IMF Finance & Development", "https://www.imf.org/en/Publications/fandd", "Global"],
    ["World Economic Forum Reports", "https://www.weforum.org/reports", "Global"],
    ["McKinsey Insights", "https://www.mckinsey.com/featured-insights", "Global"],
    ["Bruegel Datasets", "https://www.bruegel.org/datasets", "Europe"],
    ["Peterson Institute Research", "https://www.piie.com/research", "North America"],
    ["Bank for International Settlements Papers", "https://www.bis.org/publ", "Global"],
    ["OECD Economic Outlook", "https://www.oecd.org/economic-outlook", "Global"],
    ["Conference Board Leading Indicators", "https://www.conference-board.org/topics/business-cycle-indicators", "Global"],
    ["Moody's Analytics Economy", "https://www.economy.com", "Global"],
    ["Statista Research Department", "https://www.statista.com/aboutus/our-research-commitment", "Global"],
  ]),

  // ── Extended coverage #3 — Oceania/frontier institutions & more media ───────
  ...S("central-bank", [
    ["Bank of Papua New Guinea", "https://www.bankpng.gov.pg", "Oceania"],
    ["Reserve Bank of Fiji", "https://www.rbf.gov.fj", "Oceania"],
    ["Central Bank of Samoa", "https://www.cbs.gov.ws", "Oceania"],
    ["National Reserve Bank of Tonga", "https://www.reservebank.to", "Oceania"],
    ["Central Bank of Solomon Islands", "https://www.cbsi.com.sb", "Oceania"],
    ["Da Afghanistan Bank", "https://www.dab.gov.af", "Asia"],
    ["National Bank of Cambodia (data)", "https://www.nbc.gov.kh/english", "Asia"],
    ["Central Bank of Barbados", "https://www.centralbank.org.bb", "Latin America"],
  ]),
  ...S("exchange", [
    ["PNGX Markets (Papua New Guinea)", "https://www.pngx.com.pg", "Oceania"],
    ["South Pacific Stock Exchange (Fiji)", "https://www.spx.com.fj", "Oceania"],
    ["Iraq Stock Exchange", "http://www.isx-iq.net", "Middle East"],
    ["Palestine Exchange", "https://www.pex.ps", "Middle East"],
    ["Beirut Stock Exchange", "https://www.bse.com.lb", "Middle East"],
    ["Trop-X / Seychelles Securities Exchange", "https://www.merj.exchange", "Africa"],
    ["Namibian Stock Exchange", "https://nsx.com.na", "Africa"],
    ["Lusaka Securities Exchange (Zambia)", "https://luse.co.zm", "Africa"],
  ]),
  ...S("markets-data", [
    ["LSEG (London Stock Exchange Group)", "https://www.lseg.com", "Global"],
    ["S&P Global Market Intelligence", "https://www.spglobal.com/marketintelligence", "Global"],
    ["Bloomberg Tax", "https://pro.bloombergtax.com", "Global"],
    ["Data USA", "https://datausa.io", "North America"],
    ["Numbeo Markets", "https://www.numbeo.com/cost-of-living", "Global"],
    ["Refinitiv Lipper Fund Data", "https://lipperalpha.refinitiv.com", "Global"],
  ]),
  ...S("financial-news", [
    ["CNBC Africa", "https://www.cnbcafrica.com", "Africa"],
    ["CNBC-TV18 (India)", "https://www.cnbctv18.com", "Asia"],
    ["NDTV Profit (India)", "https://www.ndtvprofit.com", "Asia"],
    ["The Financial Express (India)", "https://www.financialexpress.com", "Asia"],
    ["Business Post (Ireland)", "https://www.businesspost.ie", "Europe"],
    ["BusinessTech (South Africa)", "https://businesstech.co.za", "Africa"],
    ["TechCabal (Africa)", "https://techcabal.com", "Africa"],
    ["The Independent (Uganda)", "https://www.independent.co.ug", "Africa"],
    ["Investment News (US)", "https://www.investmentnews.com", "North America"],
    ["Reuters India Markets", "https://www.reuters.com/markets/asia", "Asia"],
    ["Nikkei Markets Asia", "https://asia.nikkei.com/Business/Markets", "Asia"],
    ["Bloomberg Middle East", "https://www.bloomberg.com/middleeast", "Middle East"],
    ["Reuters Sustainable Business", "https://www.reuters.com/sustainability", "Global"],
    ["The Wall Street Journal Economy", "https://www.wsj.com/economy", "North America"],
    ["Financial Times Emerging Markets", "https://www.ft.com/emerging-markets", "Global"],
  ]),
  ...S("general-news", [
    ["Reuters Africa", "https://www.reuters.com/world/africa", "Africa"],
    ["Reuters Asia", "https://www.reuters.com/world/asia-pacific", "Asia"],
    ["Reuters Europe", "https://www.reuters.com/world/europe", "Europe"],
    ["Reuters Middle East", "https://www.reuters.com/world/middle-east", "Middle East"],
    ["Reuters Americas", "https://www.reuters.com/world/americas", "Latin America"],
    ["AP World News", "https://apnews.com/hub/world-news", "Global"],
    ["The Guardian Global Development", "https://www.theguardian.com/global-development", "Global"],
    ["BBC News Mundo (Spanish)", "https://www.bbc.com/mundo", "Latin America"],
    ["Deutsche Welle Español", "https://www.dw.com/es", "Latin America"],
    ["France 24 Español", "https://www.france24.com/es", "Latin America"],
  ]),
];

export const AUTHORITATIVE_SOURCE_COUNT = AUTHORITATIVE_SOURCES.length;

// ── Selection helpers ─────────────────────────────────────────────────────────

// Always-included global anchors — the most authoritative, broadly-useful sources.
const CORE_ANCHOR_NAMES = new Set([
  "Yahoo Finance", "Bloomberg", "Reuters", "Financial Times", "The Wall Street Journal",
  "CNBC", "International Monetary Fund (IMF)", "World Bank", "OECD", "Trading Economics",
]);

const REGION_KEYWORDS: Record<SourceRegion, string[]> = {
  "Global": [],
  "North America": ["usa", "u.s.", "united states", "america", "canada", "canadian", "mexico", "fed", "federal reserve", "wall street", "nasdaq", "nyse", "dollar", "sec"],
  "Europe": ["europe", "european", "eu ", "eurozone", "euro", "uk", "britain", "british", "germany", "german", "france", "french", "spain", "italy", "ecb", "ftse", "dax"],
  "Asia": ["asia", "asian", "china", "chinese", "india", "indian", "japan", "japanese", "korea", "singapore", "hong kong", "indonesia", "vietnam", "yuan", "rupee", "yen", "nifty", "sensex", "nikkei"],
  "Africa": ["africa", "african", "nigeria", "kenya", "south africa", "ghana", "egypt", "naira", "cedi", "shilling", "rand", "jse"],
  "Middle East": ["middle east", "gulf", "saudi", "uae", "dubai", "qatar", "kuwait", "israel", "turkey", "turkish", "riyal", "dirham"],
  "Latin America": ["latin america", "brazil", "brazilian", "mexico", "argentina", "chile", "colombia", "peru", "real", "peso", "bovespa"],
  "Oceania": ["australia", "australian", "new zealand", "asx", "aussie", "kiwi"],
};

const CATEGORY_KEYWORDS: Record<SourceCategory, string[]> = {
  "markets-data": ["stock", "share", "price", "ticker", "index", "market", "trading", "valuation", "p/e", "dividend"],
  "financial-news": ["earnings", "ipo", "merger", "acquisition", "deal", "startup", "funding", "quarterly", "revenue", "ceo"],
  "general-news": ["news", "election", "policy", "war", "crisis", "event", "happening", "today", "latest", "current", "breaking"],
  "central-bank": ["interest rate", "central bank", "monetary policy", "rate hike", "rate cut", "inflation", "fed", "ecb", "boe"],
  "regulator": ["regulation", "regulator", "compliance", "sec filing", "lawsuit", "fine", "sanction", "securities"],
  "exchange": ["exchange", "listed", "listing", "delisting", "ipo", "bourse"],
  "statistics": ["gdp", "unemployment", "inflation", "cpi", "statistics", "census", "population", "economic data", "growth rate"],
  "multilateral": ["imf", "world bank", "oecd", "global economy", "trade", "development", "forecast", "outlook"],
  "government": ["government", "budget", "fiscal", "treasury", "tax", "deficit", "debt", "spending", "policy"],
  "ratings-research": ["rating", "credit rating", "downgrade", "upgrade", "research", "report", "analysis", "forecast"],
  "commodities-energy": ["oil", "gas", "commodity", "gold", "silver", "copper", "energy", "crude", "brent", "wheat", "opec"],
  "crypto": ["crypto", "bitcoin", "ethereum", "blockchain", "token", "defi", "btc", "eth", "stablecoin"],
};

/**
 * Pick a bounded, relevant set of authoritative sources for a query. Always
 * includes the global anchors, then adds sources whose region/category keywords
 * appear in the question, then fills with globals. Bounded so we inject a useful
 * shortlist (not all ~1000) into a prompt.
 */
export function pickAuthoritativeSources(query: string, limit = 24): AuthoritativeSource[] {
  const q = ` ${query.toLowerCase()} `;
  const picked: AuthoritativeSource[] = [];
  const seen = new Set<string>();
  const add = (s: AuthoritativeSource) => { if (!seen.has(s.name)) { seen.add(s.name); picked.push(s); } };

  // Anchors first, but capped at half the budget so region/category-specific
  // sources (e.g. the relevant central bank, exchange, or regional press) always
  // get room — otherwise the 10 global anchors would swamp a small shortlist.
  const anchorCap = Math.max(4, Math.floor(limit / 2));
  for (const s of AUTHORITATIVE_SOURCES) {
    if (picked.length >= anchorCap) break;
    if (CORE_ANCHOR_NAMES.has(s.name)) add(s);
  }

  const regionHit = (r: SourceRegion) => REGION_KEYWORDS[r].some((k) => q.includes(k));
  const categoryHit = (c: SourceCategory) => CATEGORY_KEYWORDS[c].some((k) => q.includes(k));

  // Score every source by region + category relevance.
  const scored = AUTHORITATIVE_SOURCES
    .map((s) => ({ s, score: (regionHit(s.region) ? 2 : 0) + (categoryHit(s.category) ? 2 : (s.region === "Global" ? 1 : 0)) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);
  for (const { s } of scored) { if (picked.length >= limit) break; add(s); }

  // Fill remainder with globals if still short.
  if (picked.length < limit) for (const s of AUTHORITATIVE_SOURCES) {
    if (picked.length >= limit) break;
    if (s.region === "Global") add(s);
  }
  return picked.slice(0, limit);
}
