export type PageType =
  | "tool"
  | "service"
  | "paper-type"
  | "subject"
  | "software-specific"
  | "method-specific"
  | "financial-analysis"
  | "use-case"
  | "problem-solution"
  | "comparison"
  | "academic-level"
  | "citation-guide"
  | "ebook-type"
  | "ebook-platform"
  | "how-to";

export interface PageSpec {
  slug: string;
  type: PageType;
  title: string;
  metaDescription: string;
  keywords: string[];
  toolFocus?: string;
  softwareFocus?: string;
  paperTypeFocus?: string;
  financialFocus?: string;
  audienceSegment?: string;
  priority: number;
}

export const PAGE_CATALOG: PageSpec[] = [
  // ── TYPE 1: PILLAR TOOL & SERVICE PAGES (priority 1.0) ─────────────────────
  {
    slug: "ai-paper-writer",
    type: "tool",
    title: "AI Paper Writer — Academic Writing Assistance | LightspeedGhost",
    metaDescription: "AI-powered academic writing assistance for all 70+ paper types. Real citations, APA/MLA/Chicago, grade-optimised output. From $4.99/month.",
    keywords: ["ai paper writer", "ai academic writing", "ai essay writer", "academic writing assistance", "ai writing tool"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-writing-assistant",
    type: "tool",
    title: "AI Writing Assistant for Students | LightspeedGhost",
    metaDescription: "AI writing assistant that helps students improve essay quality, structure arguments, and write with proper academic register. 24/7 academic writing support.",
    keywords: ["ai writing assistant", "academic writing assistant", "writing help for students", "ai writing support"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-text-refinement",
    type: "tool",
    title: "AI Text Refinement — Natural Language Enhancement | LightspeedGhost",
    metaDescription: "Improve AI-written text naturalness and writing authenticity. Reduce AI writing patterns, enhance academic voice, and refine writing style. From $1.99.",
    keywords: ["ai text refinement", "natural language enhancement", "writing style improvement", "reduce ai writing patterns", "ai text improvement"],
    toolFocus: "humanizer",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-plagiarism-checker",
    type: "tool",
    title: "AI & Plagiarism Checker — Dual Detection | LightspeedGhost",
    metaDescription: "Check AI content probability and plagiarism similarity in one scan. 99B+ academic sources. Detailed report with flagged passages. $1.99/check.",
    keywords: ["ai plagiarism checker", "plagiarism detector", "ai content checker", "plagiarism detection tool", "ai detection"],
    toolFocus: "plagiarism",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "stem-problem-solver",
    type: "tool",
    title: "STEM Problem Solver — Step-by-Step Solutions | LightspeedGhost",
    metaDescription: "Step-by-step STEM solutions for maths, physics, chemistry, biology, engineering, CS, statistics, and finance. With graphs and worked examples. $1.99/problem.",
    keywords: ["stem problem solver", "maths problem solver", "physics homework help", "chemistry solver", "stem homework help"],
    toolFocus: "stem",
    audienceSegment: "stem-student",
    priority: 1.0,
  },
  {
    slug: "apa-citation-generator",
    type: "tool",
    title: "APA Citation Generator — All 17 Citation Styles | LightspeedGhost",
    metaDescription: "Generate perfect citations in APA 7th, MLA 9th, Chicago, Harvard, OSCOLA, Vancouver, IEEE, and 11 more styles. Export BibTeX, RIS, Zotero. Free with subscription.",
    keywords: ["apa citation generator", "citation generator", "reference generator", "mla citation", "harvard referencing generator"],
    toolFocus: "citation",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-essay-revision",
    type: "tool",
    title: "AI Essay Revision — Grade Improvement Tool | LightspeedGhost",
    metaDescription: "AI-powered draft revision that improves academic register, argument strength, and coherence. See tracked changes and estimated grade uplift. Targets First/2:1/A.",
    keywords: ["ai essay revision", "essay improvement tool", "grade improvement", "essay editing ai", "academic draft revision"],
    toolFocus: "revision",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-outline-generator",
    type: "tool",
    title: "AI Outline Generator — All Paper Types | LightspeedGhost",
    metaDescription: "Generate structured paper outlines with thesis statements, section headings, and argument sequencing for all 70+ paper types. $1.99 per outline.",
    keywords: ["ai outline generator", "essay outline generator", "paper outline tool", "research paper outline", "academic outline generator"],
    toolFocus: "outline",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "ai-study-assistant",
    type: "tool",
    title: "AI Study Assistant — 24/7 Academic Tutoring | LightspeedGhost",
    metaDescription: "24/7 AI study assistant for concept explanations, worked examples, essay planning, flashcards, and exam preparation across all subjects.",
    keywords: ["ai study assistant", "ai tutor", "ai homework help", "study assistant ai", "academic ai assistant"],
    toolFocus: "study",
    audienceSegment: "student",
    priority: 1.0,
  },
  {
    slug: "data-analysis-service",
    type: "service",
    title: "Data Analysis Service for Students & Researchers | LightspeedGhost",
    metaDescription: "Complete statistical data analysis service. SPSS, R, Stata, Python, SAS and 25+ software tools. APA-formatted results, dissertation write-up ready. From $9.99.",
    keywords: ["data analysis service", "statistical analysis help", "dissertation data analysis", "spss help", "r statistical analysis"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 1.0,
  },
  {
    slug: "financial-statement-analysis",
    type: "service",
    title: "Financial Statement Analysis Service | LightspeedGhost",
    metaDescription: "Full financial statement analysis: income statement, balance sheet, cash flows, ratios, DuPont, DCF, Altman Z-Score. CFA-standard write-ups. From $12.99.",
    keywords: ["financial statement analysis", "financial ratio analysis", "cfa financial analysis", "acca financial reporting", "financial analysis help"],
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 1.0,
  },
  {
    slug: "ai-ebook-generator",
    type: "tool",
    title: "AI Ebook Generator — All Types & Publishing Platforms | LightspeedGhost",
    metaDescription: "Generate full ebooks for business, coaching, non-fiction, and fiction. KDP, Apple Books, Gumroad ready. $29.99/month add-on.",
    keywords: ["ai ebook generator", "ai ebook creator", "create ebook with ai", "ai book generator", "ebook writing tool"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 1.0,
  },
  {
    slug: "statistical-analysis-help",
    type: "service",
    title: "Statistical Analysis Help for Dissertations | LightspeedGhost",
    metaDescription: "Expert statistical analysis help for dissertations, theses, and research papers. All tests, all software, full write-up in APA/Harvard format. From $14.99.",
    keywords: ["statistical analysis help", "statistics help students", "dissertation statistics", "statistical analysis service", "stats help"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 1.0,
  },

  // ── TYPE 2: PAPER TYPE PAGES (~70 pages, priority 0.9) ──────────────────────
  {
    slug: "ai-argumentative-essay-help",
    type: "paper-type",
    title: "AI Argumentative Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for argumentative essays. Strong thesis, logical evidence, counter-argument structure. 500–1,500 words. APA, MLA, Chicago. From $4.99.",
    keywords: ["argumentative essay help", "ai argumentative essay", "write argumentative essay", "argumentative essay writer"],
    paperTypeFocus: "argumentative-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-literature-review-help",
    type: "paper-type",
    title: "AI Literature Review Writing Help | LightspeedGhost",
    metaDescription: "AI-assisted literature review writing with real academic citations. Thematic synthesis, gap analysis, critical evaluation. 1,000–3,500 words. From $4.99.",
    keywords: ["literature review help", "ai literature review", "literature review writer", "how to write literature review"],
    paperTypeFocus: "literature-review",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-research-paper-writer",
    type: "paper-type",
    title: "AI Research Paper Writer — With Real Citations | LightspeedGhost",
    metaDescription: "AI research paper writing assistance with verified academic citations. IMRAD structure, APA/MLA/Chicago. 1,500–3,500 words. Plagiarism-checked output.",
    keywords: ["ai research paper writer", "research paper help", "write research paper ai", "research paper writing tool"],
    paperTypeFocus: "research-paper",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-dissertation-writing-assistance",
    type: "paper-type",
    title: "AI Dissertation Writing Assistance | LightspeedGhost",
    metaDescription: "AI-powered dissertation writing assistance for undergrad, masters, and PhD. Full chapters, methodology, literature review, data analysis write-up. From $39.99.",
    keywords: ["dissertation writing help", "ai dissertation writer", "dissertation assistance", "dissertation help ai"],
    paperTypeFocus: "dissertation",
    toolFocus: "paper-writer",
    audienceSegment: "postgraduate",
    priority: 0.9,
  },
  {
    slug: "ai-case-study-help",
    type: "paper-type",
    title: "AI Case Study Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for business and academic case studies. Problem identification, analysis frameworks, recommendations. 1,500–3,500 words. From $4.99.",
    keywords: ["case study help", "ai case study writer", "business case study help", "write case study ai"],
    paperTypeFocus: "case-study",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-lab-report-writer",
    type: "paper-type",
    title: "AI Lab Report Writing Help — IMRAD Format | LightspeedGhost",
    metaDescription: "AI-assisted lab report writing in IMRAD scientific format. Methods, results, discussion, conclusion sections. Biology, chemistry, physics labs. From $4.99.",
    keywords: ["lab report help", "ai lab report writer", "lab report writing tool", "scientific lab report help"],
    paperTypeFocus: "lab-report",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-essay-help",
    type: "paper-type",
    title: "AI Essay Writing Help — All Essay Types | LightspeedGhost",
    metaDescription: "AI essay writing assistance for argumentative, analytical, expository, narrative, and compare-contrast essays. All academic levels. Citations included.",
    keywords: ["ai essay help", "essay writing assistance", "essay writer ai", "academic essay help"],
    paperTypeFocus: "essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-personal-statement-help",
    type: "paper-type",
    title: "AI Personal Statement Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for university personal statements and statements of purpose. Compelling narrative, structured argument, admissions-ready output.",
    keywords: ["personal statement help", "ai personal statement", "statement of purpose writer", "personal statement writing tool"],
    paperTypeFocus: "personal-statement",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-systematic-review-help",
    type: "paper-type",
    title: "AI Systematic Review Writing Help | LightspeedGhost",
    metaDescription: "AI assistance for systematic review papers with PRISMA protocol, inclusion/exclusion criteria, evidence synthesis and meta-analysis write-up. From $34.99.",
    keywords: ["systematic review help", "ai systematic review", "systematic review writer", "systematic literature review help"],
    paperTypeFocus: "systematic-review",
    toolFocus: "paper-writer",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "ai-annotated-bibliography-help",
    type: "paper-type",
    title: "AI Annotated Bibliography Generator | LightspeedGhost",
    metaDescription: "Generate complete annotated bibliographies with source summaries, evaluations, and citations in APA, MLA, Chicago, or Harvard style. From $4.99.",
    keywords: ["annotated bibliography help", "ai annotated bibliography", "annotated bibliography generator", "bibliography writer"],
    paperTypeFocus: "annotated-bibliography",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-reflective-essay-help",
    type: "paper-type",
    title: "AI Reflective Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for reflective essays and reflective practice papers. Gibbs cycle, Kolb's model, first-person academic voice. From $4.99.",
    keywords: ["reflective essay help", "ai reflective essay", "reflective writing help", "reflection paper writer"],
    paperTypeFocus: "reflective-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-term-paper-help",
    type: "paper-type",
    title: "AI Term Paper Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for term papers across all subjects and levels. Structured argument, cited sources, formatted output in APA/MLA/Chicago. From $4.99.",
    keywords: ["term paper help", "ai term paper writer", "term paper writing assistance", "write my term paper"],
    paperTypeFocus: "term-paper",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-capstone-project-help",
    type: "paper-type",
    title: "AI Capstone Project Writing Help | LightspeedGhost",
    metaDescription: "AI-assisted capstone project writing with research design, analysis, and professional presentation. All disciplines. Academic and professional formats.",
    keywords: ["capstone project help", "ai capstone project", "capstone writing assistance", "capstone paper help"],
    paperTypeFocus: "capstone-project",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-business-plan-help",
    type: "paper-type",
    title: "AI Business Plan Writing Help (Academic) | LightspeedGhost",
    metaDescription: "AI writing assistance for academic business plans. Executive summary, market analysis, financial projections, operations plan. Harvard/MBA format.",
    keywords: ["business plan help academic", "ai business plan writer", "academic business plan", "business plan writing assistance"],
    paperTypeFocus: "business-plan",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-white-paper-help",
    type: "paper-type",
    title: "AI White Paper Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for academic and professional white papers. Problem-solution format, evidence-based argumentation, professional formatting.",
    keywords: ["white paper help", "ai white paper writer", "write white paper", "white paper writing tool"],
    paperTypeFocus: "white-paper",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-policy-brief-help",
    type: "paper-type",
    title: "AI Policy Brief Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for policy briefs and policy papers. Evidence-based recommendations, executive summary, structured argument. Government/academic format.",
    keywords: ["policy brief help", "ai policy brief writer", "policy paper writing assistance", "write policy brief"],
    paperTypeFocus: "policy-brief",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-grant-proposal-help",
    type: "paper-type",
    title: "AI Grant Proposal Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for research grant proposals. Specific aims, significance, innovation, approach sections. NIH, NSF, ESRC format guidance.",
    keywords: ["grant proposal help", "ai grant proposal writer", "research grant proposal", "grant writing assistance"],
    paperTypeFocus: "grant-proposal",
    toolFocus: "paper-writer",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "ai-research-proposal-help",
    type: "paper-type",
    title: "AI Research Proposal Writing Help | LightspeedGhost",
    metaDescription: "AI-assisted research proposal writing with research questions, methodology, literature rationale, and timeline. 800–2,500 words. From $24.99.",
    keywords: ["research proposal help", "ai research proposal", "research proposal writer", "write research proposal"],
    paperTypeFocus: "research-proposal",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-nursing-care-plan-help",
    type: "paper-type",
    title: "AI Nursing Care Plan Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for nursing care plans and SOAP notes. NANDA diagnoses, NIC interventions, NOC outcomes, evidence-based practice.",
    keywords: ["nursing care plan help", "ai nursing care plan", "soap note writer", "nursing paper help", "nursing essay ai"],
    paperTypeFocus: "nursing-care-plan",
    toolFocus: "paper-writer",
    audienceSegment: "nursing-student",
    priority: 0.9,
  },
  {
    slug: "ai-legal-brief-writing-help",
    type: "paper-type",
    title: "AI Legal Brief Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for legal briefs, legal memos, and legal analysis papers. IRAC structure, case law integration, OSCOLA/Bluebook citation.",
    keywords: ["legal brief help", "ai legal brief writer", "law essay help", "legal memo writer", "legal writing assistance"],
    paperTypeFocus: "legal-brief",
    toolFocus: "paper-writer",
    audienceSegment: "law-student",
    priority: 0.9,
  },
  {
    slug: "ai-report-writing-help",
    type: "paper-type",
    title: "AI Report Writing Help — All Report Types | LightspeedGhost",
    metaDescription: "AI writing assistance for academic and technical reports. Lab reports, technical reports, business reports, financial reports. Professional formatting.",
    keywords: ["report writing help", "ai report writer", "academic report help", "technical report writing"],
    paperTypeFocus: "report",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-persuasive-essay-help",
    type: "paper-type",
    title: "AI Persuasive Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for persuasive essays. Ethos, pathos, logos structure, compelling evidence, strong call to action. 500–1,500 words.",
    keywords: ["persuasive essay help", "ai persuasive essay", "write persuasive essay", "persuasive writing assistance"],
    paperTypeFocus: "persuasive-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-expository-essay-help",
    type: "paper-type",
    title: "AI Expository Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for expository essays. Clear explanation, factual evidence, logical structure. 500–1,500 words. All citation styles.",
    keywords: ["expository essay help", "ai expository essay", "write expository essay", "expository writing tool"],
    paperTypeFocus: "expository-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-thesis-writing-help",
    type: "paper-type",
    title: "AI Thesis Writing Help — Masters & PhD | LightspeedGhost",
    metaDescription: "AI writing assistance for masters and PhD theses. All chapters: introduction, literature review, methodology, findings, discussion, conclusion. From $39.99.",
    keywords: ["thesis writing help", "ai thesis writer", "phd thesis help", "masters thesis assistance", "thesis writing tool"],
    paperTypeFocus: "thesis",
    toolFocus: "paper-writer",
    audienceSegment: "postgraduate",
    priority: 0.9,
  },
  {
    slug: "ai-analytical-essay-help",
    type: "paper-type",
    title: "AI Analytical Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for analytical essays. Deep textual analysis, critical evaluation, evidence-based argument. 500–1,500 words. All citation styles.",
    keywords: ["analytical essay help", "ai analytical essay", "analysis essay writer", "critical analysis essay"],
    paperTypeFocus: "analytical-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-scholarship-essay-help",
    type: "paper-type",
    title: "AI Scholarship Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for scholarship essays. Compelling personal narrative, achievement framing, committee-ready formatting. All scholarship types.",
    keywords: ["scholarship essay help", "ai scholarship essay", "scholarship application essay", "write scholarship essay"],
    paperTypeFocus: "scholarship-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-admission-essay-help",
    type: "paper-type",
    title: "AI Admissions Essay Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for college and graduate school admissions essays. Authentic voice, compelling story, admissions committee optimised.",
    keywords: ["admissions essay help", "ai admissions essay", "college essay help", "university application essay"],
    paperTypeFocus: "admission-essay",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-book-review-help",
    type: "paper-type",
    title: "AI Book Review Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for book reviews and book reports. Summary, critical evaluation, theme analysis, citation-ready output.",
    keywords: ["book review help", "ai book review writer", "write book review", "book report help"],
    paperTypeFocus: "book-review",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-swot-analysis-help",
    type: "paper-type",
    title: "AI SWOT Analysis Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for SWOT analyses, PEST/PESTLE analyses, and Porter's Five Forces papers. Business strategy frameworks with citations.",
    keywords: ["swot analysis help", "ai swot analysis", "swot analysis writer", "pestle analysis help", "business analysis tool"],
    paperTypeFocus: "swot-analysis",
    toolFocus: "paper-writer",
    priority: 0.9,
  },
  {
    slug: "ai-journal-article-help",
    type: "paper-type",
    title: "AI Journal Article Writing Help | LightspeedGhost",
    metaDescription: "AI writing assistance for journal article manuscripts. Abstract, introduction, methods, results, discussion. Publication-ready academic writing. From $29.99.",
    keywords: ["journal article help", "ai journal article writer", "academic paper writing", "journal manuscript help"],
    paperTypeFocus: "journal-article",
    toolFocus: "paper-writer",
    audienceSegment: "researcher",
    priority: 0.9,
  },

  // ── TYPE 3: SUBJECT PAGES (~30 pages, priority 0.7) ─────────────────────────
  {
    slug: "ai-nursing-essay-help",
    type: "subject",
    title: "AI Nursing Essay Help — All Nursing Paper Types | LightspeedGhost",
    metaDescription: "AI writing assistance for nursing essays, care plans, SOAP notes, and clinical reflections. Evidence-based practice, NMC standards. All citation styles.",
    keywords: ["nursing essay help", "nursing paper writing", "ai nursing essay", "nursing assignment help"],
    toolFocus: "paper-writer",
    audienceSegment: "nursing-student",
    priority: 0.7,
  },
  {
    slug: "psychology-assignment-help",
    type: "subject",
    title: "Psychology Assignment Help — AI Writing Support | LightspeedGhost",
    metaDescription: "AI writing assistance for psychology essays, case formulations, research papers, and literature reviews. APA 7th edition. All psychology subfields.",
    keywords: ["psychology assignment help", "psychology essay help", "ai psychology paper", "psychology writing assistance"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "law-essay-writing-help",
    type: "subject",
    title: "Law Essay Writing Help — AI Legal Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for law essays, legal briefs, and case analyses. IRAC structure, case law integration, OSCOLA/Bluebook citation. All law subjects.",
    keywords: ["law essay help", "legal essay writing", "ai law essay", "law assignment help"],
    toolFocus: "paper-writer",
    audienceSegment: "law-student",
    priority: 0.7,
  },
  {
    slug: "economics-dissertation-help",
    type: "subject",
    title: "Economics Dissertation Help — AI Writing & Analysis | LightspeedGhost",
    metaDescription: "AI writing and data analysis assistance for economics dissertations. Econometrics, regression, time series, policy analysis. APA/Harvard format.",
    keywords: ["economics dissertation help", "economics assignment help", "economics essay ai", "econometrics help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "business-assignment-help",
    type: "subject",
    title: "Business Assignment Help — AI Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for business essays, case studies, marketing plans, and business reports. MBA and undergraduate level. Harvard Business style.",
    keywords: ["business assignment help", "business essay help", "ai business paper", "mba assignment help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "sociology-essay-help",
    type: "subject",
    title: "Sociology Essay Help — AI Academic Writing | LightspeedGhost",
    metaDescription: "AI writing assistance for sociology essays, research papers, and literature reviews. Theoretical frameworks, ASA citation, qualitative analysis.",
    keywords: ["sociology essay help", "sociology assignment help", "ai sociology paper", "sociology writing assistance"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "history-essay-help",
    type: "subject",
    title: "History Essay Help — AI Academic Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for history essays, research papers, and dissertations. Primary source analysis, Chicago/Turabian citation. All historical periods.",
    keywords: ["history essay help", "history assignment help", "ai history essay", "history paper writing"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "english-essay-help",
    type: "subject",
    title: "English Essay Help — AI Literary Analysis Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for English literature essays, critical analysis, and close reading papers. MLA 9th edition. All literary periods and genres.",
    keywords: ["english essay help", "literary analysis help", "ai english essay", "english literature assignment help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "management-assignment-help",
    type: "subject",
    title: "Management Assignment Help — AI Writing Support | LightspeedGhost",
    metaDescription: "AI writing assistance for management essays, strategic analysis, and case studies. Leadership theories, organisational behaviour, Harvard style.",
    keywords: ["management assignment help", "management essay help", "ai management paper", "business management help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },
  {
    slug: "public-health-essay-help",
    type: "subject",
    title: "Public Health Essay Help — AI Writing & Research | LightspeedGhost",
    metaDescription: "AI writing assistance for public health essays, epidemiology papers, and health policy briefs. Vancouver/APA citation. Evidence-based practice.",
    keywords: ["public health essay help", "epidemiology assignment help", "health policy essay", "public health paper"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.7,
  },

  // ── TYPE 4: STATISTICAL SOFTWARE PAGES (~30 pages, priority 0.9) ────────────
  {
    slug: "spss-analysis-help",
    type: "software-specific",
    title: "SPSS Analysis Help — Dissertation & Research | LightspeedGhost",
    metaDescription: "Expert SPSS data analysis help for dissertations and research. All SPSS tests: t-test, ANOVA, regression, factor analysis, reliability. APA write-up included.",
    keywords: ["spss help", "spss analysis help", "spss dissertation help", "spss statistics help", "ibm spss help"],
    softwareFocus: "SPSS",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "r-statistical-analysis-help",
    type: "software-specific",
    title: "R Statistical Analysis Help — Dissertation Support | LightspeedGhost",
    metaDescription: "R and RStudio statistical analysis help for dissertations. tidyverse, ggplot2, lme4, lavaan, and all major R packages. Full write-up in APA format.",
    keywords: ["r statistical analysis help", "r programming help", "rstudio help", "r dissertation help", "tidyverse help"],
    softwareFocus: "R",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "stata-dissertation-analysis",
    type: "software-specific",
    title: "Stata Analysis Help — Dissertation & Research | LightspeedGhost",
    metaDescription: "Stata data analysis help for dissertations. Panel data, time series, regression, IV estimation. All Stata versions 16–18. Complete APA write-up.",
    keywords: ["stata help", "stata analysis help", "stata dissertation help", "stata statistics help", "stata econometrics"],
    softwareFocus: "Stata",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "python-statistical-analysis",
    type: "software-specific",
    title: "Python Statistical Analysis Help | LightspeedGhost",
    metaDescription: "Python statistical analysis help using pandas, NumPy, SciPy, statsmodels, and scikit-learn. Dissertation and research paper write-up included.",
    keywords: ["python statistical analysis", "python data analysis help", "pandas help", "scipy help", "statsmodels dissertation"],
    softwareFocus: "Python",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "nvivo-qualitative-analysis-help",
    type: "software-specific",
    title: "NVivo Qualitative Analysis Help | LightspeedGhost",
    metaDescription: "NVivo qualitative data analysis help for dissertations. Thematic analysis, grounded theory, content analysis. Full methodology and findings write-up.",
    keywords: ["nvivo help", "nvivo analysis help", "nvivo dissertation help", "qualitative analysis nvivo", "nvivo thematic analysis"],
    softwareFocus: "NVivo",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "jasp-analysis-service",
    type: "software-specific",
    title: "JASP Analysis Help — Bayesian & Frequentist | LightspeedGhost",
    metaDescription: "JASP statistical analysis help including Bayesian t-tests, ANOVA, regression, and factor analysis. APA-ready output interpretation and dissertation write-up.",
    keywords: ["jasp help", "jasp analysis help", "bayesian statistics help", "jasp dissertation", "jasp vs spss"],
    softwareFocus: "JASP",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "sas-analysis-help",
    type: "software-specific",
    title: "SAS Statistical Analysis Help — All Procedures | LightspeedGhost",
    metaDescription: "SAS data analysis help for dissertations and research. PROC MEANS, FREQ, REG, LOGISTIC, MIXED, ANOVA. Base SAS and SAS/STAT. Full write-up.",
    keywords: ["sas help", "sas analysis help", "sas statistics help", "sas dissertation help", "sas programming help"],
    softwareFocus: "SAS",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "eviews-econometrics-help",
    type: "software-specific",
    title: "EViews Econometrics Analysis Help | LightspeedGhost",
    metaDescription: "EViews econometrics analysis help. Time series, VAR, VECM, GARCH, cointegration, unit root tests. Dissertation write-up in APA/Harvard format.",
    keywords: ["eviews help", "eviews econometrics help", "time series analysis eviews", "var model help", "eviews dissertation"],
    softwareFocus: "EViews",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "mplus-sem-help",
    type: "software-specific",
    title: "Mplus SEM Help — Structural Equation Modelling | LightspeedGhost",
    metaDescription: "Mplus SEM analysis help. CFA, full SEM, multilevel modelling, growth curve, mixture models. Dissertation write-up with interpretation. From $79.99.",
    keywords: ["mplus help", "mplus sem help", "structural equation modelling help", "mplus dissertation", "mplus cfa help"],
    softwareFocus: "MPlus",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "graphpad-prism-analysis-help",
    type: "software-specific",
    title: "GraphPad Prism Analysis Help — Biomedical | LightspeedGhost",
    metaDescription: "GraphPad Prism analysis help for biomedical and clinical research. t-tests, ANOVA, survival curves, nonlinear regression. Complete figure legends and write-up.",
    keywords: ["graphpad prism help", "prism statistics help", "graphpad analysis help", "biomedical statistics help"],
    softwareFocus: "GraphPad Prism",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "excel-statistical-analysis-help",
    type: "software-specific",
    title: "Excel Statistical Analysis Help | LightspeedGhost",
    metaDescription: "Excel statistical analysis help using Analysis ToolPak, XLSTAT, and Solver. t-tests, ANOVA, regression, forecasting. Dissertation write-up included.",
    keywords: ["excel statistics help", "excel analysis toolpak help", "xlstat help", "excel regression help", "excel dissertation analysis"],
    softwareFocus: "Excel",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "smartpls-sem-help",
    type: "software-specific",
    title: "SmartPLS Help — PLS-SEM Analysis | LightspeedGhost",
    metaDescription: "SmartPLS PLS-SEM analysis help. Path models, mediation, moderation, HTMT validity, bootstrapping. Full write-up for dissertations and journal articles.",
    keywords: ["smartpls help", "pls-sem help", "smartpls dissertation", "partial least squares sem help", "pls path modelling"],
    softwareFocus: "SmartPLS",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "revman-meta-analysis-help",
    type: "software-specific",
    title: "RevMan Meta-Analysis Help — Systematic Reviews | LightspeedGhost",
    metaDescription: "RevMan meta-analysis help for systematic reviews. Forest plots, funnel plots, heterogeneity, risk of bias. Full PRISMA-compliant write-up. From $79.99.",
    keywords: ["revman help", "meta-analysis help", "systematic review meta-analysis", "revman forest plot", "cochrane revman help"],
    softwareFocus: "RevMan",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "jamovi-analysis-help",
    type: "software-specific",
    title: "Jamovi Statistical Analysis Help | LightspeedGhost",
    metaDescription: "Jamovi statistical analysis help for dissertations. t-tests, ANOVA, regression, factor analysis, reliability. APA-formatted output interpretation.",
    keywords: ["jamovi help", "jamovi analysis help", "jamovi dissertation", "jamovi statistics", "jamovi vs spss"],
    softwareFocus: "Jamovi",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },
  {
    slug: "minitab-analysis-help",
    type: "software-specific",
    title: "Minitab Statistical Analysis Help | LightspeedGhost",
    metaDescription: "Minitab analysis help for quality improvement, Six Sigma, and research. Control charts, capability analysis, DOE, hypothesis testing. Full write-up.",
    keywords: ["minitab help", "minitab analysis help", "six sigma statistics help", "minitab dissertation", "minitab quality analysis"],
    softwareFocus: "Minitab",
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.9,
  },

  // ── TYPE 5: STATISTICAL METHOD PAGES (~50 pages, priority 0.8) ──────────────
  {
    slug: "regression-analysis-service",
    type: "method-specific",
    title: "Regression Analysis Help — All Types | LightspeedGhost",
    metaDescription: "Regression analysis help for dissertations: linear, multiple, logistic, ordinal, Poisson, Cox regression. All software. APA results section write-up.",
    keywords: ["regression analysis help", "regression analysis service", "multiple regression help", "logistic regression help", "regression dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "anova-analysis-help",
    type: "method-specific",
    title: "ANOVA Analysis Help — One-Way, Two-Way, MANOVA | LightspeedGhost",
    metaDescription: "ANOVA analysis help: one-way, two-way, repeated measures, MANOVA, MANCOVA, ANCOVA. All software. Post-hoc tests, effect sizes, APA write-up.",
    keywords: ["anova help", "anova analysis help", "one way anova help", "repeated measures anova", "manova help", "anova dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "sem-structural-equation-modelling-help",
    type: "method-specific",
    title: "SEM — Structural Equation Modelling Help | LightspeedGhost",
    metaDescription: "Structural equation modelling (SEM) help: CFA, path analysis, full latent SEM, mediation, moderation. Mplus, R lavaan, Amos. Complete dissertation write-up.",
    keywords: ["sem help", "structural equation modelling help", "cfa help", "path analysis help", "sem dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "thematic-analysis-service",
    type: "method-specific",
    title: "Thematic Analysis Help — Braun & Clarke | LightspeedGhost",
    metaDescription: "Thematic analysis help using Braun and Clarke 6-phase methodology. Theme development, coding, findings write-up. NVivo, MAXQDA, Atlas.ti. From $24.99.",
    keywords: ["thematic analysis help", "thematic analysis service", "braun and clarke thematic analysis", "qualitative analysis help"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "mediation-analysis-help",
    type: "method-specific",
    title: "Mediation Analysis Help — Hayes PROCESS | LightspeedGhost",
    metaDescription: "Mediation analysis help using Hayes PROCESS macro. Simple, multiple, parallel, and serial mediation. Bootstrap confidence intervals. Full APA write-up.",
    keywords: ["mediation analysis help", "hayes process help", "mediation dissertation", "simple mediation help", "serial mediation help"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "meta-analysis-service",
    type: "method-specific",
    title: "Meta-Analysis Help — Forest Plots & Publication Bias | LightspeedGhost",
    metaDescription: "Meta-analysis help: fixed and random effects, heterogeneity (I²), forest plots, funnel plots, Egger's test, subgroup analysis. From $79.99.",
    keywords: ["meta-analysis help", "meta-analysis service", "forest plot help", "systematic review meta-analysis", "meta-analysis dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "multilevel-modelling-help",
    type: "method-specific",
    title: "Multilevel Modelling Help — HLM & Mixed Models | LightspeedGhost",
    metaDescription: "Multilevel modelling (HLM/MLM) help: random effects, fixed effects, growth curves, longitudinal models. R lme4, Mplus, SPSS MIXED. Complete write-up.",
    keywords: ["multilevel modelling help", "hlm help", "hierarchical linear modelling help", "mixed models help", "mlm dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "factor-analysis-help",
    type: "method-specific",
    title: "Factor Analysis Help — EFA & CFA | LightspeedGhost",
    metaDescription: "Factor analysis help: exploratory (EFA) and confirmatory (CFA) factor analysis. Scale validation, reliability, construct validity. All software. APA write-up.",
    keywords: ["factor analysis help", "efa help", "cfa help", "exploratory factor analysis", "confirmatory factor analysis help"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "survival-analysis-help",
    type: "method-specific",
    title: "Survival Analysis Help — Kaplan-Meier & Cox | LightspeedGhost",
    metaDescription: "Survival analysis help: Kaplan-Meier curves, log-rank test, Cox proportional hazards, competing risks. R, SPSS, Stata. Full results write-up.",
    keywords: ["survival analysis help", "kaplan meier help", "cox regression help", "time-to-event analysis", "survival analysis dissertation"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "time-series-analysis-help",
    type: "method-specific",
    title: "Time Series Analysis Help — ARIMA, VAR, GARCH | LightspeedGhost",
    metaDescription: "Time series analysis help: ARIMA, GARCH, VAR, VECM, cointegration, Granger causality. EViews, R, Stata, Python. Full econometrics dissertation write-up.",
    keywords: ["time series analysis help", "arima help", "var model help", "garch model help", "cointegration test help"],
    toolFocus: "data-analysis",
    audienceSegment: "researcher",
    priority: 0.8,
  },
  {
    slug: "how-to-run-regression-in-spss",
    type: "how-to",
    title: "How to Run Regression in SPSS — Step-by-Step | LightspeedGhost",
    metaDescription: "Step-by-step guide to running linear and multiple regression in SPSS. Output interpretation, assumption testing, APA results section with example.",
    keywords: ["run regression in spss", "spss regression tutorial", "multiple regression spss", "spss linear regression guide"],
    softwareFocus: "SPSS",
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "how-to-run-anova-in-spss",
    type: "how-to",
    title: "How to Run ANOVA in SPSS — One-Way & Two-Way | LightspeedGhost",
    metaDescription: "Complete guide to running one-way and two-way ANOVA in SPSS. Post-hoc tests, effect sizes, assumption testing, and APA write-up example.",
    keywords: ["run anova in spss", "anova spss tutorial", "one way anova spss", "spss anova guide"],
    softwareFocus: "SPSS",
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "how-to-run-thematic-analysis-nvivo",
    type: "how-to",
    title: "How to Run Thematic Analysis in NVivo | LightspeedGhost",
    metaDescription: "Step-by-step guide to thematic analysis in NVivo. Creating nodes, coding data, theme development using Braun and Clarke methodology. With examples.",
    keywords: ["thematic analysis nvivo", "nvivo coding guide", "nvivo thematic analysis tutorial", "how to code in nvivo"],
    softwareFocus: "NVivo",
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "how-to-run-sem-in-r",
    type: "how-to",
    title: "How to Run SEM in R Using lavaan | LightspeedGhost",
    metaDescription: "Step-by-step guide to structural equation modelling in R with lavaan. CFA, path models, full SEM, fit indices interpretation, APA write-up example.",
    keywords: ["sem in r", "lavaan tutorial", "cfa in r", "structural equation modelling r", "r sem guide"],
    softwareFocus: "R",
    toolFocus: "data-analysis",
    priority: 0.8,
  },

  // ── TYPE 6: FINANCIAL STATEMENT PAGES (~25 pages, priority 0.9) ─────────────
  {
    slug: "income-statement-analysis",
    type: "financial-analysis",
    title: "Income Statement Analysis Help — P&L | LightspeedGhost",
    metaDescription: "Income statement analysis help: revenue, gross profit, EBIT, EBITDA, EPS, comprehensive income. IFRS 15 and US GAAP ASC 606. CFA-standard write-up.",
    keywords: ["income statement analysis", "profit and loss analysis", "income statement help", "p&l analysis", "income statement interpretation"],
    financialFocus: "income-statement",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "balance-sheet-analysis",
    type: "financial-analysis",
    title: "Balance Sheet Analysis Help | LightspeedGhost",
    metaDescription: "Balance sheet analysis: assets, liabilities, equity analysis, working capital, capital structure. IFRS and US GAAP. Financial ratio computation included.",
    keywords: ["balance sheet analysis", "balance sheet help", "financial position analysis", "balance sheet interpretation"],
    financialFocus: "balance-sheet",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "cash-flow-statement-analysis",
    type: "financial-analysis",
    title: "Cash Flow Statement Analysis Help | LightspeedGhost",
    metaDescription: "Cash flow statement analysis: direct and indirect method, operating/investing/financing activities, free cash flow, cash conversion cycle.",
    keywords: ["cash flow statement analysis", "cash flow analysis help", "statement of cash flows", "free cash flow analysis"],
    financialFocus: "cash-flow-statement",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "financial-ratio-analysis",
    type: "financial-analysis",
    title: "Financial Ratio Analysis Help — All Ratios | LightspeedGhost",
    metaDescription: "Complete financial ratio analysis: liquidity, profitability, leverage, efficiency, and market ratios. Industry benchmarks, DuPont decomposition. From $19.99.",
    keywords: ["financial ratio analysis", "financial ratios help", "ratio analysis help", "financial ratio calculator", "ratio analysis service"],
    financialFocus: "ratio-analysis",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "dupont-analysis",
    type: "financial-analysis",
    title: "DuPont Analysis Help — 3-Factor & 5-Factor | LightspeedGhost",
    metaDescription: "DuPont analysis help: 3-factor ROE decomposition and 5-factor extended DuPont. Profit margin, asset turnover, financial leverage. Written interpretation.",
    keywords: ["dupont analysis", "dupont analysis help", "roe decomposition", "dupont formula", "3 factor dupont analysis"],
    financialFocus: "dupont-analysis",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "dcf-valuation-help",
    type: "financial-analysis",
    title: "DCF Valuation Help — Discounted Cash Flow Analysis | LightspeedGhost",
    metaDescription: "DCF valuation help: WACC calculation, free cash flow projection, terminal value (Gordon Growth and Exit Multiple). Investment analysis write-up. From $44.99.",
    keywords: ["dcf valuation help", "discounted cash flow help", "wacc calculation help", "dcf model help", "dcf analysis service"],
    financialFocus: "dcf-valuation",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "ifrs-financial-statements",
    type: "financial-analysis",
    title: "IFRS Financial Statements Help | LightspeedGhost",
    metaDescription: "IFRS financial statements help: IFRS 9, 15, 16, 17 and full IFRS suite. Financial accounting assignments, ACCA/ACA/CFA exam preparation.",
    keywords: ["ifrs financial statements help", "ifrs 15 help", "ifrs 16 help", "ifrs accounting help", "acca financial reporting"],
    financialFocus: "ifrs",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "cfa-financial-analysis-help",
    type: "financial-analysis",
    title: "CFA Financial Analysis Help — Level 1, 2 & 3 | LightspeedGhost",
    metaDescription: "CFA exam financial analysis help. FRA, equity valuation, portfolio management. CFA Level 1, 2, and 3 curriculum coverage. Written analysis assignments.",
    keywords: ["cfa financial analysis help", "cfa level 1 help", "cfa fra help", "cfa equity valuation help", "cfa assignment help"],
    financialFocus: "cfa-analysis",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "altman-z-score-analysis",
    type: "financial-analysis",
    title: "Altman Z-Score Analysis Help | LightspeedGhost",
    metaDescription: "Altman Z-Score analysis: original model, revised model, and Emerging Markets model. Bankruptcy prediction with complete interpretation and benchmarks.",
    keywords: ["altman z-score", "z-score analysis help", "bankruptcy prediction model", "altman z score calculator", "financial distress analysis"],
    financialFocus: "altman-z-score",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },
  {
    slug: "acca-financial-reporting-help",
    type: "financial-analysis",
    title: "ACCA Financial Reporting Help — F7, SBR | LightspeedGhost",
    metaDescription: "ACCA financial reporting exam help. F3/FA, F7/FR, P2/SBR papers. Financial statements, consolidations, IFRS standards, exam technique.",
    keywords: ["acca financial reporting help", "acca f7 help", "acca sbr help", "acca exam help", "acca assignment help"],
    financialFocus: "acca",
    toolFocus: "financial-analysis",
    audienceSegment: "finance-student",
    priority: 0.9,
  },

  // ── TYPE 7: SELECTED USE-CASE PAGES (priority 0.8) ──────────────────────────
  {
    slug: "how-to-write-literature-review-with-ai",
    type: "use-case",
    title: "How to Write a Literature Review with AI | LightspeedGhost",
    metaDescription: "Step-by-step guide to writing a literature review using AI writing assistance. Source selection, synthesis, gap analysis, and critical evaluation with examples.",
    keywords: ["how to write literature review with ai", "ai literature review guide", "write lit review ai", "literature review tips"],
    toolFocus: "paper-writer",
    priority: 0.8,
  },
  {
    slug: "spss-analysis-for-psychology-dissertation",
    type: "use-case",
    title: "SPSS Analysis for Psychology Dissertation | LightspeedGhost",
    metaDescription: "SPSS analysis guide for psychology dissertations. t-tests, correlation, ANOVA, regression, reliability. APA 7th edition results write-up with worked examples.",
    keywords: ["spss psychology dissertation", "spss for psychology", "psychology data analysis spss", "spss dissertation psychology"],
    softwareFocus: "SPSS",
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "r-analysis-for-social-science-dissertation",
    type: "use-case",
    title: "R Analysis for Social Science Dissertation | LightspeedGhost",
    metaDescription: "R statistical analysis guide for social science dissertations. All major tests, ggplot2 visualisation, APA write-up. Step-by-step with code examples.",
    keywords: ["r social science dissertation", "r for social science", "r analysis social science", "social science statistics r"],
    softwareFocus: "R",
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "how-to-improve-essay-writing-quality",
    type: "problem-solution",
    title: "How to Improve Essay Writing Quality with AI | LightspeedGhost",
    metaDescription: "Practical guide to improving academic essay quality using AI writing assistance. Structure, argument, evidence, and academic register improvement tips.",
    keywords: ["improve essay writing quality", "better essay writing", "improve academic writing", "essay quality improvement"],
    toolFocus: "paper-writer",
    priority: 0.7,
  },
  {
    slug: "how-to-write-apa-results-section",
    type: "problem-solution",
    title: "How to Write an APA Results Section | LightspeedGhost",
    metaDescription: "Complete guide to writing APA 7th edition results sections for quantitative studies. Statistics reporting, table formatting, figure captions, and worked examples.",
    keywords: ["apa results section", "write apa results section", "apa statistics reporting", "how to write results section apa"],
    toolFocus: "data-analysis",
    priority: 0.7,
  },
  {
    slug: "how-to-check-normality-spss",
    type: "problem-solution",
    title: "How to Test Normality in SPSS | LightspeedGhost",
    metaDescription: "Step-by-step guide to normality testing in SPSS: Shapiro-Wilk, Kolmogorov-Smirnov, Q-Q plots, histograms. Interpret results and choose parametric vs non-parametric tests.",
    keywords: ["normality test spss", "shapiro wilk spss", "test normality spss", "how to check normality spss", "spss normality"],
    softwareFocus: "SPSS",
    toolFocus: "data-analysis",
    priority: 0.7,
  },
  {
    slug: "how-to-calculate-current-ratio",
    type: "problem-solution",
    title: "How to Calculate the Current Ratio | LightspeedGhost",
    metaDescription: "Complete guide to calculating and interpreting the current ratio. Formula, worked example, industry benchmarks, DuPont context, and financial analysis write-up.",
    keywords: ["current ratio calculation", "how to calculate current ratio", "current ratio formula", "liquidity ratio help"],
    financialFocus: "liquidity-ratios",
    toolFocus: "financial-analysis",
    priority: 0.7,
  },
  {
    slug: "how-to-reduce-ai-writing-patterns",
    type: "problem-solution",
    title: "How to Reduce AI Writing Patterns in Academic Work | LightspeedGhost",
    metaDescription: "Practical guide to improving writing naturalness and reducing AI writing patterns. Sentence variation, authentic voice, style refinement techniques.",
    keywords: ["reduce ai writing patterns", "improve writing naturalness", "ai writing patterns", "natural writing style", "writing authenticity"],
    toolFocus: "humanizer",
    priority: 0.7,
  },
  {
    slug: "how-to-interpret-regression-output",
    type: "problem-solution",
    title: "How to Interpret Regression Output | LightspeedGhost",
    metaDescription: "Complete guide to interpreting regression output: R², F-statistic, coefficients, p-values, confidence intervals, and multicollinearity. APA reporting included.",
    keywords: ["interpret regression output", "regression results interpretation", "regression output spss", "how to read regression output"],
    toolFocus: "data-analysis",
    priority: 0.7,
  },
  {
    slug: "how-to-read-financial-statements",
    type: "problem-solution",
    title: "How to Read Financial Statements | LightspeedGhost",
    metaDescription: "Beginner's guide to reading income statements, balance sheets, and cash flow statements. Key line items, ratios, and what to look for. With worked examples.",
    keywords: ["how to read financial statements", "understanding financial statements", "financial statements for beginners", "financial statement analysis guide"],
    toolFocus: "financial-analysis",
    priority: 0.7,
  },

  // ── TYPE 8: COMPARISON PAGES (priority 0.8) ──────────────────────────────────
  {
    slug: "spss-vs-r-for-dissertation-analysis",
    type: "comparison",
    title: "SPSS vs R for Dissertation Analysis — Full Comparison | LightspeedGhost",
    metaDescription: "SPSS vs R comparison for dissertation analysis: ease of use, capabilities, cost, output quality, and which to choose for your research. Detailed 2026 comparison.",
    keywords: ["spss vs r", "spss vs r dissertation", "spss or r for research", "r vs spss comparison"],
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "r-vs-python-for-research",
    type: "comparison",
    title: "R vs Python for Statistical Research — 2026 Guide | LightspeedGhost",
    metaDescription: "R vs Python comparison for academic research: statistical capabilities, visualisation, machine learning, package ecosystems, and which is best for your discipline.",
    keywords: ["r vs python", "r vs python statistics", "r vs python research", "python vs r data analysis"],
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "jasp-vs-spss",
    type: "comparison",
    title: "JASP vs SPSS — Which is Better for Dissertation? | LightspeedGhost",
    metaDescription: "JASP vs SPSS comparison: Bayesian vs frequentist stats, free vs paid, output quality, ease of use, and best choice for dissertation analysis.",
    keywords: ["jasp vs spss", "jasp or spss dissertation", "jasp vs spss comparison", "bayesian vs frequentist statistics software"],
    toolFocus: "data-analysis",
    priority: 0.8,
  },
  {
    slug: "best-data-analysis-service-for-dissertation",
    type: "comparison",
    title: "Best Data Analysis Service for Dissertation 2026 | LightspeedGhost",
    metaDescription: "Compare the best data analysis services for dissertations. Features, pricing, turnaround, software support, and why LightspeedGhost covers all 28 software tools.",
    keywords: ["best data analysis service dissertation", "dissertation statistics help service", "data analysis dissertation service comparison"],
    toolFocus: "data-analysis",
    priority: 0.8,
  },

  // ── TYPE 9: ACADEMIC LEVEL PAGES (priority 0.8) ─────────────────────────────
  {
    slug: "dissertation-writing-help",
    type: "academic-level",
    title: "Dissertation Writing Help — All Chapters | LightspeedGhost",
    metaDescription: "Comprehensive dissertation writing assistance. Introduction, literature review, methodology, results, discussion, conclusion. All disciplines. From $39.99.",
    keywords: ["dissertation writing help", "dissertation assistance", "dissertation writing service", "dissertation help"],
    toolFocus: "paper-writer",
    audienceSegment: "postgraduate",
    priority: 0.8,
  },
  {
    slug: "masters-dissertation-help",
    type: "academic-level",
    title: "Masters Dissertation Help — AI Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for masters dissertations across all disciplines. Full chapters, data analysis, literature review. From $39.99.",
    keywords: ["masters dissertation help", "masters thesis help", "ma dissertation assistance", "msc dissertation writing"],
    toolFocus: "paper-writer",
    audienceSegment: "postgraduate",
    priority: 0.8,
  },
  {
    slug: "phd-thesis-writing-assistance",
    type: "academic-level",
    title: "PhD Thesis Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for PhD theses and doctoral dissertations. All chapters, literature synthesis, methodology chapters. From $59.99.",
    keywords: ["phd thesis help", "phd dissertation help", "doctoral thesis writing", "phd writing assistance"],
    toolFocus: "paper-writer",
    audienceSegment: "postgraduate",
    priority: 0.8,
  },
  {
    slug: "undergraduate-essay-help",
    type: "academic-level",
    title: "Undergraduate Essay Help — AI Writing Assistance | LightspeedGhost",
    metaDescription: "AI writing assistance for undergraduate essays, term papers, and assignments across all subjects and disciplines. First class standard. From $4.99.",
    keywords: ["undergraduate essay help", "college essay help", "undergraduate assignment help", "first year university essay help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.8,
  },
  {
    slug: "mba-assignment-help",
    type: "academic-level",
    title: "MBA Assignment Help — AI Writing & Analysis | LightspeedGhost",
    metaDescription: "AI writing and analysis assistance for MBA assignments: case studies, business plans, strategic reports, financial analysis. Harvard Business School format.",
    keywords: ["mba assignment help", "mba essay help", "business school assignment help", "mba case study help"],
    toolFocus: "paper-writer",
    audienceSegment: "student",
    priority: 0.8,
  },

  // ── TYPE 10: CITATION GUIDES (priority 0.6) ──────────────────────────────────
  {
    slug: "apa-7th-edition-guide",
    type: "citation-guide",
    title: "APA 7th Edition Complete Guide | LightspeedGhost",
    metaDescription: "Complete APA 7th edition referencing guide. In-text citations, reference list formatting, all source types, DOI formatting. Free citation generator included.",
    keywords: ["apa 7th edition", "apa referencing guide", "apa citation guide", "apa 7 format", "apa style guide"],
    toolFocus: "citation",
    priority: 0.6,
  },
  {
    slug: "mla-9th-edition-guide",
    type: "citation-guide",
    title: "MLA 9th Edition Complete Guide | LightspeedGhost",
    metaDescription: "Complete MLA 9th edition style guide. Works cited page, in-text citations, all source types with examples. Free MLA citation generator.",
    keywords: ["mla 9th edition", "mla referencing guide", "mla citation guide", "mla 9 format", "mla works cited"],
    toolFocus: "citation",
    priority: 0.6,
  },
  {
    slug: "harvard-referencing-guide",
    type: "citation-guide",
    title: "Harvard Referencing Complete Guide | LightspeedGhost",
    metaDescription: "Complete Harvard referencing guide (UK standard). In-text citations, reference list, author-date format, all source types with examples. Free generator.",
    keywords: ["harvard referencing guide", "harvard citation guide", "harvard style referencing", "harvard reference format"],
    toolFocus: "citation",
    priority: 0.6,
  },
  {
    slug: "oscola-citation-guide",
    type: "citation-guide",
    title: "OSCOLA Citation Guide for Law Students | LightspeedGhost",
    metaDescription: "Complete OSCOLA 4th edition citation guide for law students. Cases, legislation, journal articles, books, EU law. Footnote format with examples.",
    keywords: ["oscola citation guide", "oscola referencing", "law referencing guide", "oscola format", "oscola style guide"],
    toolFocus: "citation",
    audienceSegment: "law-student",
    priority: 0.6,
  },
  {
    slug: "chicago-referencing-guide",
    type: "citation-guide",
    title: "Chicago Style Referencing Guide 17th Edition | LightspeedGhost",
    metaDescription: "Chicago 17th edition referencing guide. Notes-bibliography and author-date systems. Footnotes, bibliography, all source types with examples.",
    keywords: ["chicago referencing guide", "chicago style citation", "chicago 17th edition", "turabian referencing", "chicago notes bibliography"],
    toolFocus: "citation",
    priority: 0.6,
  },
  {
    slug: "vancouver-referencing-guide",
    type: "citation-guide",
    title: "Vancouver Referencing Guide for Medical Papers | LightspeedGhost",
    metaDescription: "Complete Vancouver referencing guide for medical and health sciences. Numbered references, all source types, PubMed format. Free Vancouver citation generator.",
    keywords: ["vancouver referencing guide", "vancouver citation guide", "medical referencing guide", "nlm citation guide", "vancouver style"],
    toolFocus: "citation",
    audienceSegment: "nursing-student",
    priority: 0.6,
  },
  {
    slug: "ieee-referencing-guide",
    type: "citation-guide",
    title: "IEEE Citation Guide for Engineering Students | LightspeedGhost",
    metaDescription: "Complete IEEE citation style guide for engineering and computer science. Numbered reference list, in-text brackets, all source types with examples.",
    keywords: ["ieee citation guide", "ieee referencing", "engineering referencing guide", "ieee reference format"],
    toolFocus: "citation",
    audienceSegment: "stem-student",
    priority: 0.6,
  },

  // ── TYPE 11: EBOOK TYPE PAGES (priority 0.7) ─────────────────────────────────
  {
    slug: "ai-lead-magnet-ebook-generator",
    type: "ebook-type",
    title: "AI Lead Magnet Ebook Generator | LightspeedGhost",
    metaDescription: "Generate professional lead magnet ebooks with AI. Opt-in incentives, business guides, industry reports, and free ebooks that convert. $29.99/month.",
    keywords: ["lead magnet ebook generator", "ai lead magnet creator", "create lead magnet ebook", "ai opt-in ebook"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "ai-business-ebook-generator",
    type: "ebook-type",
    title: "AI Business Ebook Generator | LightspeedGhost",
    metaDescription: "Generate professional business ebooks, guides, white papers, and thought leadership content with AI. KDP and direct-to-consumer ready. $29.99/month.",
    keywords: ["ai business ebook generator", "business ebook creator", "create business ebook ai", "professional ebook generator"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "ai-non-fiction-ebook-writer",
    type: "ebook-type",
    title: "AI Non-Fiction Ebook Writer | LightspeedGhost",
    metaDescription: "Generate complete non-fiction ebooks with AI. Self-help, health, finance, productivity, personal development. Amazon KDP and all platforms ready.",
    keywords: ["ai non-fiction ebook writer", "non-fiction ebook generator", "create non-fiction ebook ai", "ai ebook writer"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "create-ebook-with-ai",
    type: "ebook-type",
    title: "Create an Ebook with AI — Complete Guide | LightspeedGhost",
    metaDescription: "Complete guide to creating professional ebooks with AI. From concept to publication on Amazon KDP, Apple Books, Gumroad, and more. $29.99/month.",
    keywords: ["create ebook with ai", "ai ebook creation", "make ebook with ai", "ai ebook generator guide"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },

  // ── TYPE 12: EBOOK PUBLISHING PLATFORM PAGES (priority 0.7) ─────────────────
  {
    slug: "how-to-publish-ebook-amazon-kdp",
    type: "ebook-platform",
    title: "How to Publish an Ebook on Amazon KDP | LightspeedGhost",
    metaDescription: "Step-by-step guide to publishing on Amazon Kindle Direct Publishing (KDP). Formatting, pricing, 70% royalties, KDP Select, Kindle Unlimited. 2026 guide.",
    keywords: ["publish ebook amazon kdp", "amazon kdp guide", "kindle direct publishing guide", "how to self-publish kindle", "kdp publishing 2026"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "gumroad-ebook-selling",
    type: "ebook-platform",
    title: "How to Sell Ebooks on Gumroad | LightspeedGhost",
    metaDescription: "Complete guide to selling ebooks on Gumroad. Setup, pricing, 98% revenue share, audience building, and promotion strategies for digital products.",
    keywords: ["gumroad ebook selling", "sell ebooks gumroad", "gumroad guide", "gumroad digital products", "gumroad vs amazon"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "best-ebook-publishing-platform-2026",
    type: "ebook-platform",
    title: "Best Ebook Publishing Platforms 2026 — Full Comparison | LightspeedGhost",
    metaDescription: "2026 comparison of the best ebook publishing platforms: Amazon KDP, Apple Books, Kobo, Gumroad, Draft2Digital, Payhip. Royalties, reach, and best fit.",
    keywords: ["best ebook publishing platform 2026", "ebook publishing platform comparison", "where to publish ebook", "ebook distribution platforms"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
  {
    slug: "draft2digital-publishing-guide",
    type: "ebook-platform",
    title: "Draft2Digital Publishing Guide — 140+ Retailers | LightspeedGhost",
    metaDescription: "Complete Draft2Digital guide. Distribute to Amazon, Apple Books, Kobo, B&N, OverDrive, Scribd and 140+ retailers. 10% commission, easy setup.",
    keywords: ["draft2digital guide", "draft2digital publishing", "ebook aggregator guide", "wide publishing ebooks", "draft2digital vs amazon"],
    toolFocus: "ebook",
    audienceSegment: "creator",
    priority: 0.7,
  },
];

export function getCatalogByType(type: PageType): PageSpec[] {
  return PAGE_CATALOG.filter((p) => p.type === type);
}

export function getCatalogByTool(tool: string): PageSpec[] {
  return PAGE_CATALOG.filter((p) => p.toolFocus === tool);
}

export function getCatalogBySoftware(software: string): PageSpec[] {
  return PAGE_CATALOG.filter((p) => p.softwareFocus === software);
}

export function getPageSpec(slug: string): PageSpec | undefined {
  return PAGE_CATALOG.find((p) => p.slug === slug);
}
