export const ALL_SUBJECTS = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "English Literature",
  "Geography",
  "Computer Science",
  "Economics",
  "Psychology",
  "Sociology",
  "Business Studies",
  "Art & Design",
  "Music",
  "Languages",
  "Political Science",
  "Philosophy",
  "Environmental Science",
  "Statistics",
  "Medicine",
  "Law",
  "Finance",
  "Accounting",
  "Actuarial Science",
  "Insurance",
  "Credit Analysis",
  "Banking",
  "Investment",
  "Marketing",
  "Nursing",
  "Engineering",
  "Education",
  "Theology",
  "Communications",
  "Criminology",
  "Social Work",
  "Public Health",
  "Architecture",
  "Anthropology",
  "Linguistics",
  "Data Science",
  "Information Technology",
  "Supply Chain Management",
  "Human Resource Management",
  "International Relations",
  "General",
] as const;

export type SubjectName = (typeof ALL_SUBJECTS)[number];
